### ISSUE TITLE
Remove buttons from databrowser on 'upgraded' projects

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1005]
**Current behavior**
In the databrowser, the buttons 'Edit Schema', 'Add field' and 'Configure Auth Provider' are still available. The first two buttons just show a quick page refresh, but the 'Configure Auth Provider' button actually still works, which is not a good thing.

**Expected behavior?**
No 'edit-related' buttons in the Databrowser for upgraded projects.

**Comment by marktani** [comment]
Fixed! 🙂
