### ISSUE TITLE
logs.replace is not a function for local logs

### ISSUE THREAD

**Issue by timwis** [graphcool/framework#1007]
**Current behavior**
On a local cluster, after running a function that failed,
```bash
> graphcool logs
 ▸    logs.replace is not a function
```

**Expected behavior?**
Show logs

Happy to paste in a log file if it's helpful and you let me know where to find it.

**Comment by marktani** [comment]
Can you share the code of the failing function? What do you mean exactly with failing?

**Comment by timwis** [comment]
That's the thing, I'm not sure what caused it -- I tried to install that auth0/auth and run it, and it failed -- probably user error, but whatever it logged seemed to break the `graphcool logs` command.

**Comment by marktani** [comment]
Would you be able to share the directory containing the service definition (preferably as a Github repo) and the GraphQL operation that invokes the function?

The service definition includes `graphcool.yml` and all functions, permissions and GraphQL documents referred from there.

**Comment by timwis** [comment]
I've since deleted the block from `graphcool.yml` and the associated code, and the error still happens. My guess is whatever it logged is breaking the parser that the CLI uses to pretty print logs.

**Comment by timwis** [comment]
Or it's this fella: https://github.com/graphcool/graphcool/blob/c8112a7734e96f0e7eb09b48a2aaf05c348823fc/cli/packages/graphcool-cli-core/src/commands/logs/function.ts#L152

**Comment by marktani** [comment]
Ah right, that's why you asked about the logs. Will try to reproduce that error message anyway, thanks!

**Comment by timwis** [comment]
I've experienced this with the hosted service too. I started a new project, then deployed to the hosted service. I ran `graphcool add-template graphcool/templates/auth/email-password`, uncommented the appropriate lines in `graphcool.yml` and `types.graphql` (merging the `User` type in the latter) and deployed again. I ran the `signupUser` mutation in the playground and got an error:

<img width="1424" alt="screen shot 2017-10-23 at 17 35 13" src="https://user-images.githubusercontent.com/761444/31914490-dbb8dc16-b818-11e7-9da2-ec01e8d5f1c0.png">

I went to function logs and saw a record for the error:

<img width="1333" alt="screen shot 2017-10-23 at 17 37 39" src="https://user-images.githubusercontent.com/761444/31914502-ec4b96cc-b818-11e7-8c1f-6611782726ae.png">

But when I click on the error to expand it, it disappears:

<img width="1338" alt="screen shot 2017-10-23 at 17 37 44" src="https://user-images.githubusercontent.com/761444/31914511-f49e86ae-b818-11e7-9c41-e8d3a39b4505.png">

Not sure if this is helpful but here's my javascript console when the log disappears:

<img width="701" alt="screen shot 2017-10-23 at 17 38 50" src="https://user-images.githubusercontent.com/761444/31914546-19dc4f46-b819-11e7-8aa6-1ab7e37567f0.png">

And most interestingly, running `graphcool logs` in the CLI produces the same error as the original report:

<img width="675" alt="screen shot 2017-10-23 at 17 39 24" src="https://user-images.githubusercontent.com/761444/31914565-2d60ea54-b819-11e7-8286-7a9dfbc6e020.png">

Finally, this is a dog that looks like a hot dog:

![20081209-hot-dog](https://user-images.githubusercontent.com/761444/31914595-49d9f9d2-b819-11e7-847e-a8d4213d492d.jpg)

**Comment by timwis** [comment]
By modifying the CSS on the console I was able to see the full contents of the error, which pointed to the `email-password` template not passing the `name` property to `User`, which is required by the default `graphcool init` template. So when I merged the `User` types after doing `add-template ....email-password`, I didn't think to make that not required. Note that this doesn't solve the bug being reported, just more background.

**Comment by mwickett** [comment]
I know the team is travelling, but any updates on this? It's _really_ hard to develop functions when we can't see any log output.

**Comment by timwis** [comment]
FYI, upgrading to v0.8.1 resolved this for me. @mwickett can you verify? If so I'll close the issue.

**Comment by mwickett** [comment]
Yes, confirmed. Thanks!
