### ISSUE TITLE
Permission tab only works after refresh in new Console Playground

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1012]
**Current behavior**
When you open a new permission tab, the query doesn't show up, and you can't type anything, until you refresh the page.
![image](https://user-images.githubusercontent.com/852069/31947377-7a8475f6-b8d4-11e7-8907-b93046250dbd.png)

Also, closing the permissions tab breaks the layout.
![image](https://user-images.githubusercontent.com/852069/31947397-85471f34-b8d4-11e7-995d-390fa80645a4.png)

**Expected behavior?**
It just works.

**Comment by panzupa** [comment]
I have the same problem (tested in Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable))

**Comment by dukuo** [comment]
Same here, and I can't even use the queries available, such as SomeUserExists.
Google Chrome 62.0.3202.94 (64-bit)

**Comment by kbrandwijk** [comment]
This seems fixed.
