### ISSUE TITLE
Simple/Relay option missing in Console Playground

### ISSUE THREAD

**Issue by phehaz** [graphcool/framework#1013]
**Current behavior**
There is no option to change from simple to Relay in the console playground. (Or it has been moved to a position i can't find)

**Reproduction**
Open https://console.graph.cool/[ProjectName]/playground and can't find option to switch.

**Expected behavior?**
There should be a way to change between Simple and Relay in the playground.

**Comment by marktani** [comment]
More background:

> Currently, the built-in Playground in the Console is directly connected to the Simple API.
> A switch would be useful that allows to connect to the Relay API.

> This has been taken out for now, because it requires a plugin system in https://github.com/graphcool/graphql-playground.

> For now, you can directly go to the Relay API endpoint to use the Relay API from your browser, or connect to the endpoint using the stand-alone electron Playground app.

**Comment by marktani** [comment]
In Graphcool 1.0, the Simple and Relay APIs have been unified into a single Client API. Therefore, this will not be adjusted. More information about Graphcool 1.0: https://github.com/graphcool/framework/pull/1318
