### ISSUE TITLE
I install graphcool@next via nom I -g but, graphcool CLI command is not available

### ISSUE THREAD

**Issue by agustif** [graphcool/framework#1027]
➜ npm install -g graphcool@next

/Users/agustif/.asdf/installs/nodejs/8.7.0/.npm/bin/graphcool -> /Users/agustif/.asdf/installs/nodejs/8.7.0/.npm/lib/node_modules/graphcool/dist/index.js
/Users/agustif/.asdf/installs/nodejs/8.7.0/.npm/bin/gc -> /Users/agustif/.asdf/installs/nodejs/8.7.0/.npm/lib/node_modules/graphcool/dist/index.js
+ graphcool@0.8.1
updated 1 package in 13.622s

➜ graphcool
zsh: command not found: graphcool

**Comment by kbrandwijk** [comment]
Seems like that bin folder isn't in your path. Doesn't seem specific to graphcool CLI though...

**Comment by agustif** [comment]
Hey, I finally fixed this by installing with:

`npm install -g graphcool`

and then installing the latest update...

Closing this!
