### ISSUE TITLE
Exporting large data should not time out

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#1030]
For **bug reports**, please fill in the next sections:

**Current behavior**

When exporting models with many nodes, the operation currently times out.

**Expected behavior?**

We should either warn about the export not working for large data sets, or not time out.

See also https://github.com/graphcool/framework/issues/11

**Comment by alexeygolev** [comment]
Does it mean that If I have a large data set I'm effectively locked in?

**Comment by sorenbs** [comment]
@alexeygolev We are reworking the way data import/export works to provide a much better system.

If you need a short term solution, just get in touch so we can help you manually :-)

**Comment by alexeygolev** [comment]
What's the preferred way of getting in touch:) I asked Nilan through Intercom but I'm sure he is swamped with stuff lately

**Comment by sorenbs** [comment]
Intercom is the preferred way. Most of the team is currently flying back to Berlin after spending a week in SF. Expect things to be back to normal in the next 24 hours :-)

**Comment by marktani** [comment]
Please see #1299.
