### ISSUE TITLE
Specify DB columns to be indexed

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#104]
Currently, for a given model, the `id` field, all unique fields and all relations are indexed already.

**Comment by dubiousdavid** [comment]
A real game changer would be if you could specify multiple columns for an index. In particular, a unique index across more than one field allows you to constrain by, for example, userId and name, so that the name field is unique per user, but not globally unique.

**Comment by marktani** [comment]
Thanks for the suggestion @dubiousdavid, this is related to #65. :slightly_smiling_face:

**Comment by marktani** [comment]
Closing in favor of https://github.com/graphcool/framework/issues/1300. @dubiousdavid would love to hear your feedback on the linked proposal!

**Comment by Xample** [comment]
@mahkali 404 what is the status of this issue ? I am struggling with very poor performances on text search over a set of 2.5m items…

**Comment by EhsanSarshar** [comment]
So what if I directly manipulate database and set index on it. I think this will not make any issue for prisma service. I hope 🤲
