### ISSUE TITLE
Add static hosting

### ISSUE THREAD

**Issue by fdidron** [graphcool/framework#1047]
**What feature are you missing?**
I would like to deploy and serve static web applications from a graphcool cluster.

**How could this feature look like in detail? Tradeoffs?**
A bit similar to how the netlify cli works, running the command `gc deploy static` would deploy the content of a local directory set in the .graphcool.rc file . Minimum configuration should be supported such as SSL Certificates or Let's Encrypt provisioning / Redirection rules (especially for SPAs). Being able to server side render JavaScript applications would be a plus !

**Comment by kbrandwijk** [comment]
I would be really against this. I think it's way outside of the core features that a Graphcool cluster, or Graphcool in general, should offer. Why would you want this?

**Comment by sorenbs** [comment]
If the Graphcool CLI had a plugin system, would it provide value for you to have a netlify plugin to deploy static content? How should it work?

**Comment by fdidron** [comment]
@kbrandwijk I built apps on Parse an Firebase who provide(d) static hosting as part of their offering. It meant we didn't have to handle devops for the front and backend.

@sorenbs I'm not sure it would add value, the point was to be able to rely on Graphcool's reliability and scalability to serve my apps.

**Comment by kbrandwijk** [comment]
@fdidron I understand. I was referring to the fact that there are companies specializing in static hosting (like Zeit now, for example), that are completely focused on providing the best solution to that problem. I am afraid that the technical debt involved in doing this right will just take away valuable time and effort from the core systems.

**Comment by fdidron** [comment]
@kbrandwijk +1 on using now.sh . You make a valid point on the technical debt involved at this stage.
