### ISSUE TITLE
Create repo/folder for API Gateway / schema stitching examples

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1049]
Somewhere in https://github.com/graphcool-examples

**Comment by marktani** [comment]
I saw a list of your example ideas regarding this topic, could you share a link here?

**Comment by kbrandwijk** [comment]
The list is here: https://github.com/kbrandwijk/graphcool-gateway-examples/issues/1#issue-268917294 But it would be nice to have them in a graphcool-examples repo. This FR is just about creating the repo, not about filling it 😄

**Comment by marktani** [comment]
Done: https://github.com/graphcool-examples/api-gateway 🎉
