### ISSUE TITLE
Provide tooling for composing API Gateway

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1053]
This is a placeholder issue to gather specs for any tooling that could be provided to make it easier to create an API Gateway. I've played with the schema stitching, and I come across a lot of boilerplate and repetitive tasks, or things that are easier, or harder to do in a Gateway.

**Comment by sorenbs** [comment]
Based on the talks we had at GraphQL Summit, this is an area that will see a lot of development in the near future not just from Graphcool but also the broader GraphQL community. Exciting times ahead :-)

I assume you are already aware of https://github.com/graphcool/graphql-transform-schema ?

**Comment by kbrandwijk** [comment]
@sorenbs Yes I am. But it has some structural design issues and the functionality will soon be obsolete.
Regarding tooling, I was thinking more in the direction of composability, configuration etc. For example, using a similar approach to the Graphcool service definition to define a gateway:
https://gist.github.com/kbrandwijk/47a6479d9668153451eb6272818b8aa9

And other features related to using a Gateway, such as exposing tracing information, making it easy to validate a token from the Gateway (#1051), supporting arbitrary directives in your schema.

And there's also https://github.com/graphcool/graphql-boilerplate of course, so maybe that's a better place to discuss this, but it wasn't around when I created this issue.

**Comment by marktani** [comment]
Yes, let's continue the discussion there. https://github.com/graphcool/graphql-boilerplate/issues/1 and https://github.com/graphcool/graphql-boilerplate/issues/7 are good places for that.
