### ISSUE TITLE
New Console Playground does not show autocomplete options menu

### ISSUE THREAD

**Issue by panzupa** [graphcool/framework#1058]
**Current behavior**
Console intellisense / autocomplete menu works only on *query* levels (line 1 and 2 on the screen below). When hitting CTRL+SPACE on line 3 nothing shows up.
![image](https://user-images.githubusercontent.com/22025007/32093573-10125b9a-bafd-11e7-92cf-af56fea029df.png)

The same problem occurs in new tabs for permission queries (I can only get to a *filter* element, but there is no menu inside the filter).
![image](https://user-images.githubusercontent.com/22025007/32093659-7c8a7a1e-bafd-11e7-9b5e-1bf2e3b245d2.png)

**Reproduction**

Open Playground, paste 
```
query {
allUsers {
  
}
}
```
and try to bring up the menu (CTRL+SPACE) while being on line 3.
Tested on Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)

**Expected behavior?**
Autocomplete menu should be shown on all levels of the query.

**Comment by panzupa** [comment]
@marktani  any plans to fix that issue soon?

**Comment by panzupa** [comment]
Happy to see that bug was allocated to the next release :-D 👍

**Comment by kbrandwijk** [comment]
This is actually a bug in the underlying `graphiql` component, as it happens now on all enviroments that use that component (including Apollo Launchpad for example).

**Comment by panzupa** [comment]
@kbrandwijk If that's true that bug was not present before. Maybe GC team can revert to `graphiql` version that didn't have that bug?

**Comment by marktani** [comment]
This has been fixed a while ago 🙂
