### ISSUE TITLE
Is it possible to define nested structure without adding new nodes (models)?

### ISSUE THREAD

**Issue by pie6k** [graphcool/framework#1059]
Imagine `Task` model. Task may repeat and informations about that would be inside `recursion` field. 

Imagine task that is repeating like `repeat every 3rd day`.

You could then query 
```
query {
  Task(id: "id-here") {
    name
    recursion {
      interval {
        unitCount,
        unit
      }
    }
  }
}
```

and get:

```
Task: {
  name: 'Go running',
  recursion: {
    interval: {
      unitCount: 3,
      unit: 'Week'
    }
  }
}
```

Assuming I want to have only `Task` node saved in database, is it possible achieve such scenario? I imagine `recursion` would be stored as JSON, but it would be 'covered' and 'guarded' by proper schema layer.

eg.

```
type Task @model {
  id: ID! @isUnique
  name: String!
  recursion: Recursion
}

type Recursion @json {
  interval: RecursionInterval
}

type RecursionInterval @json {
  unitCount: Int!;
  unit: Unit!;
}
```

Note that such recursion might have much more fields or nesting levels eg `excludedDays`.

Needless to say, it would be awesome to be able to query parts of such fields (Postgres `jsonp` is allowing queries over json fields, but as far as I know, you use MySQL)

**Comment by sorenbs** [comment]
@pie6k can you please check that https://github.com/graphcool/framework/issues/1160 covers all your use cases?
