### ISSUE TITLE
Integrating with existing `docker-compose` setup

### ISSUE THREAD

**Issue by flux627** [graphcool/framework#1063]
When I run
```
$ gc local up
```
I see that it runs
```
$ docker-compose up -d --remove-orphans
```
Where/how is it running this? How would I go about incorporating this into my current `docker-compose.yml` file?

**Comment by kbrandwijk** [comment]
If you use `graphcool local eject`, you'll get the docker-compose file, and you have to start it yourself.

**Comment by flux627** [comment]
Perfect! Is there anything I should know before doing this (perhaps regarding upgrades)?

**Comment by kbrandwijk** [comment]
Yes, that `eject` really means: you're on your own now. But if there's a new version, you could of course always go `eject` in a new folder, and merge any changes to the `docker-compose.yml`
