### ISSUE TITLE
Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by katopz** [graphcool/framework#1064]
**Current behavior**
`Cannot read property 'subscribe' of undefined` throw after hit play button
![image](https://user-images.githubusercontent.com/97060/32116042-488a38a0-bb73-11e7-8886-c19c086246db.png)

**Reproduction**
Try to use subscriptions via playground, e.g.
```
subscription {
  Tracing(filter: {mutation_in: [CREATED]}) {
    node {
      id
    }
  }
}
```
hit play button and got error

**Expected behavior?**
Working subscription.

**Comment by ZaninAndrea** [comment]
I'm having the same problem, as a temporary solution I switched from _view as admin_ to _view as everyone_ and it worked

**Comment by schickling** [comment]
Issue moved to [graphcool/graphql-playground #231](https://github.com/graphcool/graphql-playground/issues/231) via [**ZenHub**](https://www.zenhub.com/)
