### ISSUE TITLE
Examples: Missing connect query

### ISSUE THREAD

**Issue by timwis** [graphcool/framework#1069]
I believe the "permissions" example unintentionally allows users to create posts on behalf of other users, because the "connect" permission does not verify that the inputted "user" matches the logged in user.
https://github.com/graphcool/framework/blob/master/examples/permissions/graphcool.yml#L67

Should look more like:
https://github.com/graphcool/framework/blob/master/examples/full-example/graphcool.yml#L89

**Comment by nikolasburk** [comment]
Great catch @timwis! I just updated the example with a proper permission query, thanks a lot 🙌🎉
