### ISSUE TITLE
"rest-wrapper" example is broken

### ISSUE THREAD

**Issue by pmdarrow** [graphcool/framework#1070]
**Current behavior**

Unable to query `allBreeds` in "rest-wrapper" example project using `graphcool/0.8.5 (darwin-x64) node-v8.6.0`.

**Reproduction**

1. Copy and deploy the "rest-wrapper" project from `/examples`. 
2. Try to query for `allBreeds`:
```
{
  allBreeds {
    name
  }
}
```
3. Observe the error in Playground:
```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allBreeds"
      ],
      "code": 5000,
      "message": "A function returned an unhandled error. Please check the logs for executionId 'eu-west-1:simple:cj9bvxgka004l0175qf4rww70'",
      "requestId": "eu-west-1:simple:cj9bvxgka004l0175qf4rww70"
    }
  ]
}
```

4. View `graphcool logs`:
```
2017-10-28T21:46:35.388Z 147ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: {\"logs\":[{\"stdout\":\"\"},{\"stderr\":\"\"},{\"error\":\"No content to map due to end-of-input\\n at [Source: ; line: 1, column: 0]\"}],\"response\":{\"error\":\"Function did not return a valid response. Check your function code / logs.\"}}"
}
```

**Expected behavior?**

Example to function properly.

**Comment by marktani** [comment]
Are you on the local cluster? I also get an error, but it's this one:

```graphql
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allBreeds"
      ],
      "code": 2063,
      "message": "The payloadType for the resolver is not nullable.",
      "requestId": "eu-west-1:simple:cj9c0w12dgzgs0109ywe3qnsr"
    }
  ]
}
```

**Comment by kbrandwijk** [comment]
The cause was a missing package.json, for which I have submitted a PR. For the undescriptive error message, I have created #1078.

**Comment by pmdarrow** [comment]
@marktani I receive the error on both local and remote clusters, but not that one.

**Comment by marktani** [comment]
@pmdarrow can you confirm that the missing `package.json` was the culprit?

**Comment by badrange** [comment]
@marktani I had this problem - downloaded the package.json and now it worked. Thanks!

**Comment by badrange** [comment]
Note: I had to use queries like this one: 

```
{
  viewer {
  allSubBreeds(breedName: "hound") {
    name
    }
  }
}
```

Without the "viewer" part - using examples from the docs - I get this error: 

```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'allSubBreeds' on type 'Query'. (line 2, column 3):\n  allSubBreeds(breedName: \"hound\") {\n  ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by kbrandwijk** [comment]
@badrange Did you by any chance use the Relay endpoint?

**Comment by badrange** [comment]
A bit late to the party, but answering anyway: Yes I used relay.

**Comment by badrange** [comment]
Good point: It wouldn't hurt to mention in the docs that the queries only work on the simple endpoint. Wonder if I should create an issue or not.. hmmm :)
