### ISSUE TITLE
Rename `graphcool local stop` to `graphcool local down`

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1071]
**What feature are you missing?**
`docker compose` uses `up` and `down`. `graphcool local` uses `up` and `stop`. I have seen this error message around 100 times 🙈:
```
λ graphcool local down
 !    local down is not a graphcool command.
 !    Perhaps you meant local up
 !    Run graphcool help local for a list of available commands.
```
Please either add `graphcool local down` or rename `stop` to `down`, to be more in line with `docker-compose`.

**How could this feature look like in detail? Tradeoffs?**
`graphcool local down`

**Comment by marktani** [comment]
`stop` is the combination of `down` and `kill`.

**Comment by kbrandwijk** [comment]
That still makes little sense. `docker-compose kill` is the forced version of `docker-compose stop`. Both commands do not remove the containers. `docker-compose down` does remove the containers, which `graphcool local stop` doesn't do.

**Comment by marktani** [comment]
Please bring this up in #1330. Note that the current commands are `start` and `stop`, which is not consistent with the according docker command names. This is intended.
