### ISSUE TITLE
import does not work in function .ts

### ISSUE THREAD

**Issue by steida** [graphcool/framework#1080]
This does not work in .ts file:
`import diacritics from 'diacritics-map';`

But in .js file, this works:
`const diacritics = require('diacritics-map');`

**Comment by kbrandwijk** [comment]
The module doesn't have a default export. Try `import * as diacritics from 'diacritics-map'`. Also, this has nothing to do with Graphcool.

**Comment by steida** [comment]
OK. Thank you.
