### ISSUE TITLE
'ENOENT': spawn docker-compose ENOENT

### ISSUE THREAD

**Issue by abhitheawesomecoder** [graphcool/framework#1083]
When I fire command **graphcool local up** for local deployment, I get following error :

'ENOENT': spawn docker-compose ENOENT

please check screen-shot. I have installed docker successfully on Ubuntu 16.04
![graphcoollocalerror](https://user-images.githubusercontent.com/3944526/32176284-3cecfa0a-bdad-11e7-8d9a-7a69bab40340.png)

**Comment by kbrandwijk** [comment]
Have you also installed `docker-compose`?

**Comment by abhitheawesomecoder** [comment]
no, only docker

**Comment by marktani** [comment]
Did you try installing `docker-compose`?

Also see #904.

**Comment by abhitheawesomecoder** [comment]
No because that's not mentioned in documentation

**Comment by marktani** [comment]
Can you try installing it now?
The better handling of this error message is covered in #904.

**Comment by abhitheawesomecoder** [comment]
Server is deployed now. But I am not getting the CRUD feature that is there
in graphcool server. All I am getting is graphql playground.

Is it now available in local deployment?

**Comment by marktani** [comment]
How does your deployed `types.graphql` look like?

**Comment by abhitheawesomecoder** [comment]
All screen-shots attached. What I mean to say is that I am not getting 'SCHEMA', 'DATA', 'PERMISSIONS', 'FUNCTIONS' tab as is available in graph.cool server. 
![typesgql](https://user-images.githubusercontent.com/3944526/32329592-822d80fa-c003-11e7-9039-2ba3e1944b3b.png)
![localservergui](https://user-images.githubusercontent.com/3944526/32329601-897a5720-c003-11e7-830c-31b1b871d634.png)
![graphcoolgui](https://user-images.githubusercontent.com/3944526/32329613-8fac01fc-c003-11e7-8ef2-7937e6c5ad1c.png)

**Comment by marktani** [comment]
The Console is currently only available in the Graphcool Cloud. See also: https://www.graph.cool/forum/t/graph-cool-console-for-local-development/1402?u=nilan

I'm closing this as all issues seem to be resolved. Please open a new discussion in the Forum or here on Github if you have further questions. 🙏
