### ISSUE TITLE
Incorrect subscription endpoint shown when deploying to a local cluster with different ip/hostname

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1092]
**Current behavior**
When you deploy to a local cluster with a different ip/hostname (blocked by #1091), the subscription endpoint shown is wrong:
```
  Simple API:        http://192.168.2.3:60000/simple/v1/cj9fqdxy2001s01503bxi8duy
  Relay API:         http://192.168.2.3:60000/relay/v1/cj9fqdxy2001s01503bxi8duy
  Subscriptions API: ws://localhost:60000/subscriptions/v1/cj9fqdxy2001s01503bxi8duy
```

**Reproduction**
See #1091 for reproduction steps

**Expected behavior?**
Show the correct subscription endpoint

**Comment by marktani** [comment]
This is now released in `0.9.1`: https://github.com/graphcool/framework/releases/tag/0.9.1 🙂
