### ISSUE TITLE
Permissions Leak via Relationship Fields

### ISSUE THREAD

**Issue by frankdugan3** [graphcool/framework#1095]
While this is probably a feature request, it's important enough that I'd consider the current behavior a bug. If I'm missing something that is already documented or if this is already covered clearly in an existing issue, I apologize for not searching hard enough before submitting this issue.

As it stands, there is no apparent way to limit which subfields of a relationship field are permitted. This leads to a major all-or-nothing permissions leak, even with just a few relationships.

**Current behavior**
```graphql
type User {
    superSecretField: String!
    enrollments: [Enrollment!]! @relation(name: "EnrollmentOnUser")
}

type Enrollment {
    user: User! @relation(name: "EnrollmentOnUser")
    offering: Offering! @relation(name: "EnrollmentOnOffering")
}

type Offering {
  seats: Int!
  enrollments: [Enrollment!]! @relation(name: "EnrollmentOnOffering")
  course: Course! @relation(name: "OfferingOnCourse")
}

type Course {
  title: String!
  offerings: [Offering!]! @relation(name: "OfferingOnCourse")
}

# This allows for an easy way around restricted User.read fields,
# but using relationships that are needed for basic functionality.
# Say we wanted a public page to list available course offerings
# and how many seats were still open:

{
  allOfferings {
    seats
    course { # necessary relationship
      title # need this
      offerings { # don't want this exposed
        enrollments { # even worse
          user { # oh no...
            superSecretField # MAJOR LEAK!
          }
        }
      }
    }
    _enrollmentsMeta { # want this
     count # use to figure out how many seats are left
    }
  }
}

```

**Expected behavior?**
Any or all: 
1) To be able to limit which subfields on a relation are permitted per operation.
2) For the permissions of each model to dictate what can be read when that model is accessed via a relationship on another model, unless **explicity** overridden by the permissions given by 1.

**Comment by marktani** [comment]
Permissions work on a node basis, so you can lock down access on the `superSecretField` like so:

```yaml
permissions:
  # everyone can read the id field, but not the superSecretField
  - operation: User.read
  - fields: [id]
```

**Comment by marktani** [comment]
It looks like either your permission setup is incorrect, or you are providing a token to the requests on accident.

I prepared this quick example that shows locking down fields, even when accessing them with relations: https://github.com/marktani/issue-1095

If you still experience this issue, please share a reproducible service definition in form of a Github repository, including step-by-step instructions + queries.

**Comment by frankdugan3** [comment]
@marktani OK, after doing some experimenting, I figured out what I was experiencing. My permissions settings were correct, but if a type has no data, running a query that violates permissions will return an empty array with **no errors**. Once I put data in, errors were returned. If this is expected behavior, perhaps a there should be a note about that in the permissions docs?
