### ISSUE TITLE
CLI says to use `graphcool diff` instead of `graphcool deploy --dry-run`

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/framework#1099]
**Current behavior**

When running `graphcool deploy` with potentially destructive changes, the error message written by the CLI is the following:

>    ✖ Your migration includes potentially destructive changes. Review using `graphcool diff` and continue using `graphcool deploy --force`.

**Expected behavior?**

`graphcool diff` has been removed. The CLI should warn to use `graphcool deploy --dry-run` instead.

**Comment by marktani** [comment]
duplicate of #1066
