### ISSUE TITLE
Improved data import/export

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#11]

**Comment by marceloogeda** [comment]
What about data import?

**Comment by marktani** [comment]
There's a pending PR for a JSON import using the CLI (+ other formats): https://github.com/graphcool/graphcool-cli/pull/117

**Comment by marceloogeda** [comment]
thank you @marktani for reporting :)

**Comment by marktani** [comment]
Closing in favor of #1299.

**Comment by marktani** [comment]
This has now been released in the [latest version of `graphcool-framework`](https://github.com/graphcool/framework/releases/tag/0.11.4) and the [latest developer preview of Graphcool 1.0](https://github.com/graphcool/framework/pull/1318#issuecomment-353673128) 🎉
