### ISSUE TITLE
How to sync with remote?

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1102]
_From @awesomejerry on November 1, 2017 15:28_

I currently use the legacy project. But after I upgraded the `graphcool-cli`, I need to sync my local setting with remote's schema and etc. On a legacy version, I can use `graphcool pull` to pull the changes to local. How can I achieve the same thing in new version `graphcool-cli`

_Copied from original issue: graphcool/graphql-cli#43_

**Comment by nikolasburk** [comment]
Added a section about this in the reference in the **Legacy Console Projects** chapter.
