### ISSUE TITLE
Logs are malformed

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#1108]
```
console.log('hi')
```

ends up being printed like this when saying `graphcool logs`:

```
    {
      "2017-11-01T19:55:35.694Z\t9f06f408-bf3e-11e7-aee3-b1771235a209\thi": "2017-11-01T19:55:35.694Z\t9f06f408-bf3e-11e7-aee3-b1771235a209\thi"
    }
```

**Comment by marktani** [comment]
A fix will be deployed in the next version.

**Comment by panzupa** [comment]
Will this also fix https://github.com/graphcool/framework/issues/1073 ?

**Comment by samwiseduzer** [comment]
My console.log()'s now don't appear at all - is there a flag I need to toggle somewhere?

**Comment by marktani** [comment]
This has been fixed 💯 

@samwiseduzer, your problem sounds like a separate issue, please open a new bug report 🙂
