### ISSUE TITLE
Tutorial still mentions and uses 'modules'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1116]
https://docs-next.graph.cool/docs/tutorials/auth/authentication-with-firebase-for-react-and-apollo-uh5atohthu

Also: docs\02-Concepts\01-Overview\03-GraphQL-Backend-Architecture.md

**Comment by nikolasburk** [comment]
I just removed the Firebase tutorial - we'll write an updated version once the template is ready!
