### ISSUE TITLE
Links to other docs are broken in quickstarts

### ISSUE THREAD

**Issue by kevlened** [graphcool/framework#1119]
**Current behavior**

Clicking any link to another docs page in a quickstart renders a white background

**Reproduction**

Open https://www.graph.cool/docs/quickstart/backend/typescript/typescript-rohd6ipoo4 and click any link to another graph.cool doc. All these links are missing the `/docs` path.

`https://www.graph.cool/reference/database/data-modelling-eiroozae8u` => `https://www.graph.cool/docs/reference/database/data-modelling-eiroozae8u`

**Expected behavior?**

Render the appropriate page

**Comment by timsuchanek** [comment]
Thanks for reporting @kevlened !
It is fixed and deployed :)
