### ISSUE TITLE
Interpret comments as descriptions in SDL

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1136]
**What feature are you missing?**
The SDL representation of a GraphQL schema does not allow you to define Type and Field descriptions. They are very useful for understanding a schema in the Playground docs (for example), especially for a public endpoint. Would it be possible to interpret comments in SDLs as descriptions?

**How could this feature look like in detail? Tradeoffs?**
```
# Describes the type of test
enum Test {
  # Used to describe an end-to-end test
  EndToEnd
  # Used to describe a unit test
  Unit
}
```
Same for fields and Types.

**Comment by Toosick** [comment]
👍 I saw the GraphQL PR with this and was hoping it worked with GC. Danget 😢

**Comment by marktani** [comment]
Closing in favor of https://github.com/graphcool/framework/issues/1405.
