### ISSUE TITLE
Access Relay API in built-in Console Playground

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#1147]
Currently, the built-in Playground in the Console is directly connected to the Simple API.
A switch would be useful that allows to connect to the Relay API.

This has been taken out for now, because it requires a plugin system in https://github.com/graphcool/graphql-playground.

For now, you can directly go to the Relay API endpoint to use the Relay API from your browser, or connect to the endpoint using the stand-alone electron Playground app.

**Comment by kbrandwijk** [comment]
Duplicate of #1013?

**Comment by marktani** [comment]
Yes! 😄
