### ISSUE TITLE
"SyntaxError: Unexpected token {" in legacy function

### ISSUE THREAD

**Issue by nishantvarshnay** [graphcool/framework#1151]
SyntaxError: Unexpected token { at Object.exports.runInThisContext (vm.js:53:16)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:91:32)
   at Object.defaultJavascriptCompiler [as nodejsCompiler] (/data/sandbox/lib/compiler.js:124:30)
   at module.exports.options.nodejsCompiler.fnCallback (/data/io/1fccb8ddadab43d7a4f46ad453e8065e/webtask.js:5:11)
   at /data/sandbox/lib/compiler.js:236:17
   at /data/sandbox/node_modules/async/dist/async.js:3853:24<
   at replenish (/data/sandbox/node_modules/async/dist/async.js:946:17)
   at iterateeCallback (/data/sandbox/node_modules/async/dist/async.js:931:17)
   at /data/sandbox/node_modules/async/dist/async.js:906:16
   at /data/sandbox/node_modules/async/dist/async.js:3858:13

Please suggest here.

**Comment by marktani** [comment]
Can you share the function code? Seems like you're using something like `const { a } = myObject`, which is not supported in legacy projects.

You could consider [upgrading to the Framework](https://www.graph.cool/docs/reference/service-definition/legacy-console-projects-aemieb1aev) to get access to the new function runtime that supports ES7 features.

**Comment by nishantvarshnay** [comment]
Yeah, we are using const object.

const fetch = require('isomorphic-fetch')

const url = 'https://xyz.com/'

module.exports = function (event) {

  const data = event.data.Profile.node
  const {
  	id,
    name,
    businessTitles,
    ageRange,
    visibleOnSearch,
    url,
    posts,
    region,
    socialPlatforms,
    locations,
    workRadius,
    description,
    about,
    genres,
    category,
    languages,
    specialities,
    hourlyRate,
    gender,
    currency,
    coverPhotoUrl,
    profilePhotoUrl,
    createdAt,
    updatedAt
  } = data
  
  const body = JSON.stringify(
    {
		profile: [
          {
          	id: id,
            url: url,
            createdAt: createdAt,
            updatedAt: updatedAt,
            visibleOnSearch: visibleOnSearch,
            category: category,
            name: name,
            businessTitles: businessTitles,
            specialities: specialities,
            genres: genres,
            locations: locations,
            workRadius: workRadius,
            hourlyRate: hourlyRate,
            currency: currency,
            languages: languages,
            ageRange: ageRange,
            gender: gender,
            about: about,
            description: description,
            posts: posts,
            coverPhotoUrl: coverPhotoUrl,
            profilePhotoUrl: profilePhotoUrl
          }
        ]
  })
  
  return fetch(
    url,
    {
      headers: {
        Username: 'test',
		Password: 'pwd'
      },
      method: 'PUT',
      body: body
    }
  )
  	.then(response => response.json())
  	.then(console.log)
  	.catch(console.err)
}

This is my function. Please suggest what should i do?

**Comment by marktani** [comment]
You cannot use the syntax `const { a } = myObject` in legacy functions.

These are your two options:

* Either, rewrite your function so it doesn't use that syntax.
* Or, [upgrading the service to the Framework](https://www.graph.cool/docs/reference/service-definition/legacy-console-projects-aemieb1aev). You can then use this syntax.

We will not add support for this syntac to legacy functions. Therefore, I am closing this issue. Feel free to create a new thread in the forum if you need further help with this, or chime in [here](https://www.graph.cool/forum/t/require-proper-tutorial-or-guide-to-upgrade-project/1482).

**Comment by nishantvarshnay** [comment]
Thanks @marktani
