### ISSUE TITLE
Reserved word in a field of the model

### ISSUE THREAD

**Issue by chinclubi** [graphcool/framework#1156]
Hi,
I created `Order` model type Which has a field named `time` then deployed it.

After that, I tried to run my app but received an internal server error with request id `ap-northeast-1:simple:cj9k25gmxiejo0173b4g5c2dl`

I solved a problem By renaming `time` field to another name and deployed it. The problem was solved.

I guess it is a bug, because of using `time` as a field in the model.

**Comment by marktani** [comment]
`time` is not a reserved field name. It looks like an inconsistency was introduced to your deployed service. Please reach out to support@graph.cool if you need help resolving this.
