### ISSUE TITLE
Bug cannot return non null for non-nullable type

### ISSUE THREAD

**Issue by pansitwattana** [graphcool/framework#1166]
![image](https://user-images.githubusercontent.com/12652753/32413153-e6e5d272-c23d-11e7-9c61-99331152b7ec.png)

I mutated Post with authorId maybe null but in my schema it requires author.

my mutation
```
mutation ($title: String!, $authorId: ID!, $latex: String!  $description: String, $tagName: String!, $difficulty: Difficulty){
  createPost (
    title: $title
    authorId: $authorId
    latex: $latex
    description: $description
    difficulty: $difficulty
    tags: [{
      name: $tagName
      subject: "Math"
    }]
  ) {
    id
    title
    latex
    difficulty
    description
  }
}
```

and it throw error like this
```
Error: GraphQL error: A unique constraint would be violated on Post. Details: Sorry, no more details available.
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:129
    at <anonymous>
```

it still mutates data to Post

new data null on author (it will not show any data if author field is required)
![image](https://user-images.githubusercontent.com/12652753/32413240-00caaa58-c240-11e7-884f-a24c66cf65bb.png)

and I found that It only shows error when mutate to existing Tag
``` 
tags: [{
  name: $tagName
  subject: "Math"
}]
```

**Comment by pansitwattana** [comment]
I fixed this by change User schema to Optional and it can be access again

**Comment by marktani** [comment]
This is the symptom of a more general topic covered here: #597.

**Comment by marktani** [comment]
Please continue the discussiojn there 🙂
