### ISSUE TITLE
Rename directive @isUnique to @unique

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1177]
In favour of less code to write when defining a data model I'm suggesting to rename the `@isUnique` directive to simply `@unique`. There are no other precedents of this naming scheme, so changing it here won't result in any inconsistency.

**Comment by marktani** [comment]
This is a breaking change and should be planned accordingly, similar to https://github.com/graphcool/framework/issues/817.

**Comment by schickling** [comment]
Agree. Let's introduce this with the 1.0 release.
However, this shouldn't be a problem since we can support both variants and deprecate `@isUnique` for a certain period of time to make the transition easier.

**Comment by marktani** [comment]
Closed in favor of https://github.com/graphcool/framework/issues/1380.
