### ISSUE TITLE
Subscription queries only support single field

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1188]
**Current behavior**
Executing this subscription query:
```graphql
subscription {
  Post { mutation node { id } }
  User { mutation node { id } }
}
```
Results in this error:
```json
{
  "data": null,
  "error": [
    {
      "message": "Cannot query field 'User' on type 'Subscription'. (line 3, column 3):\n  User { mutation node { id }}\n  ^"
    }
  ]
}
```

**Expected behavior?**
Either the subscription works, or a meaningful error is returned. Preferably the first option.

**Comment by marktani** [comment]
closing in favor of https://github.com/graphcool/framework/issues/214
