### ISSUE TITLE
`graphcool local up` hangs after upgrading docker images

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1196]
![image](https://user-images.githubusercontent.com/852069/32502406-eb548ba2-c3da-11e7-87d3-898ac341081a.png)

**Comment by timsuchanek** [comment]
Which version of the CLI are you running on which OS?

**Comment by kbrandwijk** [comment]
graphcool/0.9.0-alpha.2 (windows-x64) node-v9.0.0

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/32502892-3198ce9c-c3dc-11e7-8683-cfe2a8268433.png)
![image](https://user-images.githubusercontent.com/852069/32502906-388a2b92-c3dc-11e7-9a5d-f3ebd4598b14.png)

**Comment by timsuchanek** [comment]
Perfect! That is what I wanted to ask :+1:

**Comment by kbrandwijk** [comment]
This was due to the error in the 0.9 beta docker images. Is fixed in the latest images.
