### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Julianojc** [graphcool/framework#1197]
I'm trying to use the email / password (auth) template, but I'm getting this error below when I make this mutation via playground ....

```
mutation {
   signupUser (email: "alice@graph.cool" password: "graphql") {
     id
     token
   }
}
```

**** Error in playground:**
```
"code": 5000,
       "message": "A function returned an unhandled error. Please check the logs for executionId 'eu-west-1: simple: cj9ptcoeo4q690173clo00cam'",
       "requestId": "eu-west-1: simple: cj9ptcoeo4q690173clo00cam"
```

**** Error in function Log:**
`"error": "Function returned invalid status code: 0. Raw body: empty.last"`

**** I am using the Windows 10 OS, and the remote graphcool panel. And followed the steps of the README**

* I cloned the template repository
* I installed dependencies with Yarn Install
* I deployed
![1](https://user-images.githubusercontent.com/22328386/32504219-6d0e8e78-c3c6-11e7-9751-08964b42b14c.jpg)
![2](https://user-images.githubusercontent.com/22328386/32504220-6d593b26-c3c6-11e7-8c41-c55da192b770.jpg)

**Comment by marktani** [comment]
Closing in favor of #1031.
