### ISSUE TITLE
Authenticating doesn't work on Ubuntu Subsystem for Windows

### ISSUE THREAD

**Issue by mekwall** [graphcool/framework#1199]
**Current behavior**
Authenticating with `graphcool login` doesn't work on Ubuntu Subsystem for Windows.

```
$ graphcool login
Auth URL: https://console.graph.cool/cli/auth?cliToken=cj9pu9ke20000ff10w3s8v3ub&authTrigger=auth
Authenticating... ⣻
 ▸    'ENOENT': spawn cmd.exe ENOENT

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
error Command failed with exit code 1.
```
**Reproduction**
Run `graphcool login` without any previously stored credentials.

**Expected behavior?**
Authentication should work or error should be better handled.

**Comment by kbrandwijk** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/852069/32506231-4e5db440-c3e4-11e7-8950-33255864e094.png)

**Comment by mekwall** [comment]
Ah, it was an issue with Ubuntu Subsystem and it was [fixed in Windows Build 14951](https://msdn.microsoft.com/en-us/commandline/wsl/release-notes#build-14951). I am currently running Build 14393 so need to get my system upgraded.

I'll close this then.

**Comment by kbrandwijk** [comment]
@mekwall Good find, thank you for putting it here for reference.
