### ISSUE TITLE
import _ from 'lodash' undefined

### ISSUE THREAD

**Issue by Toosick** [graphcool/framework#1226]
I am trying to make a simple extend function with lodash.
___
```
import _ from 'lodash';
console.log(_);
```
returns `undefined` in the logs. Thus trying `_.zipWith` makes the function return an error.
___
`import { fromEvent } from 'graphcool-lib';` works
`import test from './test'` works
`import { test } from './test'` works
___
**Version**
`graphcool/0.9.0 (windows-x64) node-v6.10.2`
`graphcool/0.9.0 (linux-x64) node-v6.11.2`
Both hit this problem.

**Comment by kbrandwijk** [comment]
When using the import syntax, you don't import it like this. You use `import { zipWith } from 'lodash'` for example, and call `zipWith(...)` directly. Or, you can do `import * as _ from 'lodash'` and use `_.zipWith(...)`.

**Comment by Toosick** [comment]
@kbrandwijk Ok so `import _ from 'lodash';` works on my frontend because we are using Webpack/Babel. But when using the Graphcool runtime, which doesn't use Babel I'm guessing, I have to change it up to `import { zipWith } from 'lodash'` or `import * as _ from 'lodash'`?
