### ISSUE TITLE
When invoking resolver using CLI, event.context is undefined

### ISSUE THREAD

**Issue by dhruska** [graphcool/framework#1235]
To reproduce, create the following function:
```
export default async event => {
  console.log(event.context)
}
```

and run using `graphcool invoke-local`.

Additionally, when passing in an argument (for example, contactId), it is passed in as event.contactId when invoked using the CLI, but event.data.contactId when deployed. I believe the latter is the expected behavior.

**Comment by kbrandwijk** [comment]
To run `graphcool invoke-local` you need to provide either a JSON file or the lastEvent parameter. Which one caused this behavior for you? Because the only way I can reproduce this, is if the structure of the JSON you're passing in is wrong.

**Comment by dhruska** [comment]
I invoked this as:
`graphcool invoke-local --json reminderId.json` where `reminderId.json` was `{"reminderId":"abc"}`

**Comment by kbrandwijk** [comment]
@dhruska Like I expected, the JSON structure was invalid. The current `invoke-local` just passes whatever JSON to `event`. I just created a FR for validation: #1240. In the meantime, if your function is already deployed, you can use `graphcool local-invoke --lastEvent` to get a proper JSON file. The structure has to mimic:
```graphql
{
  event: { 
     data: { ... }
     context: { ... }
  }
}
```
Context is optional (unless you need it in your function)

**Comment by dhruska** [comment]
Aha - I did not realize that! I assumed the JSON was representative of the data passed in from the query. Thanks!

**Comment by dhruska** [comment]
Will try again with the updated JSON structure shortly

**Comment by dhruska** [comment]
@kbrandwijk With the following syntax, I was able to get this to work:
```
{
  data: { ... }
  context: { ... }
}
```

**Comment by kbrandwijk** [comment]
@dhruska Sorry, my mistake. I updated my earlier answer.
