### ISSUE TITLE
Reference existing node by any unique field

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#1267]
The current API has many places where it is possible to reference an existing node by id. This spec generalises that concept to work for any field combination that uniquely determines a node.

> note: This proposal use the new API design described in https://github.com/graphcool/framework/issues/353. This is WIP

## Behavior

In all places where you can currently specify a node by its primary id, we now accept an object with optional fields for each unique field on the model.

In the future we will extend this to support multi field unique constraints and unique fields on related nodes.

#### Valid

```graphql
updateUser(by: {email: "soren@graph.cool"}, data: {name: "Søren"})
```

#### Invalid

Specifying two unique fields will return a runtime error

```graphql
updateUser(by: {email: "soren@graph.cool", id: "some-id"}, data: {name: "Søren"})
```

### Nested mutation

Given this schema:

```graphql
type User @model {
  id: ID! @isUnique
  name: String
  city: City @relation(name: "UserCity")
}

type City @model {
  id: ID! @isUnique
  name: String @isUnique
  inhabitants: [City!]! @relation(name: "UserCity")
}
```

the following mutation creates a `User` and adds the existing `City` with the name 'Berlin' to the city relation:

```graphql
createUser(data: {name: "Nilan", city: {connect: {name: "Berlin"}}})
```

**Comment by kbrandwijk** [comment]
> Specifying two unique fields will return a runtime error

Why?

**Comment by sorenbs** [comment]
Good question. We could allow this. If there is no node matching both fields (even if there are nodes matching each field individually), we simply treat it as today when you supply a id that doesn't match an existing node.

**Comment by kbrandwijk** [comment]
@sorenbs Or just tweak the syntax a little like the filter arguments, and always have a `AND` and `OR` generated, so you can do `updateUser(by: { OR: [{email: "soren@graph.cool"}, {id: "some-id"}]}, data: {name: "Søren"})`, which makes it more like the traditional `UPDATE .... SET ... WHERE ... AND/OR ....`

**Comment by sorenbs** [comment]
@kbrandwijk I think it is a very nice property that the normal create/update/delete mutations only affect one node. That's why I am so obsessed with only selecting by unique fields. 

If we allow more complex selection criteria like `OR: [{email: "soren@graph.cool"}, {id: "some-id"}]` it becomes possible to select multiple nodes. We could solve that by only applying the mutation to the first node, but I really don't like the uncertainty of that approach.

If the intention is to actually operate on multiple nodes, then the new updateMany/deleteMany mutations can be used https://github.com/graphcool/framework/issues/81

**Comment by kbrandwijk** [comment]
@sorenbs I agree with you that the normal mutations should guarantee working on a single node, and should throw an error when trying to update multiple nodes. Still, I believe there is a case for using `OR` while selecting a single node.

**Comment by sorenbs** [comment]
@kbrandwijk Good point. I believe we can introduce `AND` and `OR` in the future without it being a breaking change. We will not implement it in the first version

**Comment by marktani** [comment]
Upsert mutations are a frequent feature request (see https://github.com/graphcool/framework/issues/25). Note that nested upserts (discussed in https://github.com/graphcool/framework/issues/1280) do not cover the use case of upserts.

I propose the following `updateOrCreateUser` mutation:

```graphql
updateOrCreateUser(
  by: {
    email: "soren@graph.cool"
  }
  update: {
    name: "Søren"
  }
  create: {
    name: "Søren"
    city: ...
  }
) {
  id
}
```

All fields in `update` are optional. fields in `create` are required if the according field/relational field in `types.graphql` is required.

open questions:
* I'm not exactly sure how `update` and `create` look like, but they should have a very similar shape: a valid `create` should also be a valid `update`. This makes it easier to use `updateOrCreate` in forms.
* is it enough to offer the same payload as `updateUser`? adding information whether the node was updated or created to the payload might be considered.
* Do `update` and `create` include nested mutation capabilities? Pro: convenience. Contra: complexity.

**Comment by sorenbs** [comment]
@marktani See #1340 :-)

Upsert mutations use the same input types as update and create, so the shape of input data is the exact same.

Side note - do you oppose calling it `upsert`?

**Comment by marktani** [comment]
Awesome! No, I like `upsert` 🙂

**Comment by marktani** [comment]
This feature is now available as part of *stage beta2* of [the developer preview for Graphcool 1.0](https://github.com/graphcool/framework/pull/1318#issuecomment-353674448).

**Comment by marktani** [comment]
This feature is now available as part of *stage beta2* of [the developer preview for Graphcool 1.0](https://github.com/graphcool/framework/pull/1318#issuecomment-353674448).
