### ISSUE TITLE
Invalid OR condition in permissions example

### ISSUE THREAD

**Issue by steve-a-jones** [graphcool/framework#1269]
Looks like the OR conditions in the permissions example @ framework/examples/permissions/src/permissions/User.graphql are actually ANDs..

```
query UpdateUserData ($user_id: ID!) {
  SomeUserExists(filter: {
    OR: [{
      id: $user_id,
      role: ADMIN
    }]
  })
}
```

Should actually be..

```
query UpdateUserData ($user_id: ID!) {
  SomeUserExists(filter: {
    OR: [
        {id: $user_id},
        {role: ADMIN}
      ]
  })
}
```

**Comment by gc-codesnippets** [comment]
Thanks a lot @steve-a-jones for catching this 🎉  (you're also welcome to create PRs if you recognize these kinds of issues 👍 )

**Comment by nikolasburk** [comment]
Thanks a lot @steve-a-jones for catching this 🎉 (you're also welcome to create PRs if you recognize these kinds of issues 👍 )
