### ISSUE TITLE
Disabling algolia integration

### ISSUE THREAD

**Issue by mattfysh** [graphcool/framework#1281]
Hello, is anyone else having issues disabling the legacy Algolia integration? At present, I’m unable to disable an existing active integration, and this is preventing me from upgrading the legacy project to the new Framework.

If anyone else had this problem - how did you solve it?
Were you able to create a new project and somehow copy the data over?

**Comment by marktani** [comment]
We're currently looking into a fix here.

**Comment by mattfysh** [comment]
just for some context, I tried to upgrade to Framework about a month ago... and this came up as an issue for multiple people. There was some discussion in this (now missing) thread: https://github.com/graphcool/console/issues/1295

At the time, I was able to use the System API (https://api.graph.cool/system) as a workaround ... but this no longer seems to be working:

```
mutation {
  updateSearchProviderAlgolia(input: {projectId: "",
    applicationId: "",
    apiKey: "",
    isEnabled: false
  }) {
    clientMutationId
  }
}
```

**Comment by iamclaytonray** [comment]
What is the current status on this? Also, are there any other known workarounds?

**Comment by mattfysh** [comment]
@iamclaytonray - if you're blocked on development, just create a new project with the same schema and work on the new project.

As for rolling out the update to your existing projects, if you've already completed dev against the new Graphcool Framework, and you do need to get it out to an existing deployment, the only thing I can think of is creating a new project and using that for good. The only issue is if your existing project has data, there are 2 options here:

1. try to use the "clone" feature in the console, you may get lucky and it will create a new project with all your data, but without the algolia integration enabled. I've not yet given this a try 🤞 
2. export all your data and import into a new project 🤢

**Comment by iamclaytonray** [comment]
@mattfysh - I was thinking the exact same thing as far as creating a new project. I haven't been able to figure out how to import data though. Any advice?

**Comment by mattfysh** [comment]
@iamclaytonray there's an Export Data button in the project settings... but there's no easy way to import the data AFAIK, you may need to write a manual script - and be aware the graphcool may want to assign new ID's for your objects

**Comment by iamclaytonray** [comment]
That's what I figured earlier. I just manually created a bunch of new data. No big deal.

**Comment by mattfysh** [comment]
@marktani - any idea on when this might be ready? If no, could you help us out maybe with some info on what the challenges here are. I've got no visibility into the Console codebase, but I imagine the difficulty is trying to reverse changes to the deployment that enabling Algolia made?

**Comment by marktani** [comment]
Please reach out to `support@graph.cool` if you need help with disabling the Algolia integration, until we fixed this issue 🙂

**Comment by marktani** [comment]
This should now work again, otherwise reach out to `support@graph.cool`.
