### ISSUE TITLE
NO RESOURCE FOUND

### ISSUE THREAD

**Issue by aljibbs** [graphcool/framework#1290]
**Current behavior**
I get a no resource found error (404) but I know the resource is there. When I use the Graphcool playground, I get the needed results.

**Reproduction**

> $.post({
        url: 'https://api.graph.cool/simple/v1/cj9xk9bwb04t60163vd201m1n',
              processData: false,
              data: JSON.stringify(`{ allInvitations { id firstName } }`),
              contentType: 'application/json'
        }).done(function (response) {
             console.log('Fetched Invitations:', response.data.allInvitations);
        });

**Comment by marktani** [comment]
Hey @aljibbs, your report contains not enough information to get any insights into what's going on. How to reproduce this error message? Where is it coming from?

Thanks! 🙂

**Comment by marktani** [comment]
Hey @aljibbs, closing this for now. Please provide more information if you still experience any problems!
