### ISSUE TITLE
Strange behavior with required/non-required fields

### ISSUE THREAD

**Issue by zlandau** [graphcool/framework#1292]
**Current behavior**

I have a type that looks like this:

```
  type Item @model {
  createdAt: DateTime!
  description: String!
  file: File! @relation(name: "ItemOnFile")
  id: ID! @isUnique
  name: String
  storage: Storage! @relation(name: "ItemOnStorage")
  tags: [Tag!]! @relation(name: "ItemOnTag")
  upc: String
  updatedAt: DateTime!
  user: User @relation(name: "UserOnItem")
}
```

but generated simple schema looks like this:

```
type Item implements Node {
  createdAt: DateTime!
  description: String!
  file(filter: FileFilter): File!
  id: ID!
  name: String
  storage(filter: StorageFilter): Storage!
  tags(filter: TagFilter, orderBy: TagOrderBy, skip: Int, after: String, before: String, first: Int, last: Int): [Tag!]
  upc: String
  updatedAt: DateTime!
  user(filter: UserFilter): User

  # Meta information about the query.
  _tagsMeta(filter: TagFilter, orderBy: TagOrderBy, skip: Int, after: String, before: String, first: Int, last: Int): _QueryMeta!
}
```

And to create an item:

```
  createItem(description: String!, name: String, upc: String, fileId: ID, file: ItemfileFile, storageId: ID, storage: ItemstorageStorage, userId: ID, user: ItemuserUser, tagsIds: [ID!], tags: [ItemtagsTag!]): Item
```

There are a couple things strange about this. For one, the upc field is still showing up as a 'String' type rather than 'String!'. Also, in createItem, description is String! but when I try to create an item I get an error:

```
GraphQL error: Variable '$description' expected value of type 'String!' but value is null. Reason: Expected non-null value, found null.
```

It really seems like the wrong schema is being used. So I tried removing the .graphcoolrc file and re-deploying, but I get the same schema. I'm fetching the schema with the following .graphqlconfig.yaml file, which seems right to me:

```
schemaPath: schema.graphql
extensions:
  endpoints:
    simple:
      url: 'https://api.graph.cool/simple/v1/cja47hm2f06br0144e1nz74by'
      subscription: 'wss://subscriptions.us-west-2.graph.cool/v1/cja47hm2f06br0144e1nz74by'
```

**Reproduction**

Using the schema as above may help reproduce it.

**Expected behavior?**

I expect 'name' to be required, but no other fields. So description, upc, storage, etc shouldn't need to be defined.

**Comment by marktani** [comment]
>   description: String!
>   name: String

> I expect 'name' to be required, but no other fields. So description, upc, storage, etc shouldn't need to be defined.

`description` is required, while `name` is not.

**Comment by kbrandwijk** [comment]
> For one, the upc field is still showing up as a 'String' type rather than 'String!'

Also, `upc` is defined as `String` in your type, so why would you expect it to be `String!`?

**Comment by zlandau2** [comment]
I can't believe I got this far without realizing that ! meant required, not nullable. I shall now go hang my head in shame.

**Comment by marktani** [comment]
Please don't :slightly_smiling_face:
