### ISSUE TITLE
Unable to add credentials for Algolia integration from the console (legacy project)

### ISSUE THREAD

**Issue by patrick-samy** [graphcool/framework#1304]
[Legacy project]

**Current behavior**

When adding Algolia credentials to my project on the console, I'm getting the following error:

> Please check that the Application ID and API Key is correct. You can find both on the API Keys page in the Algolia web interface. You must create a new API Key and enable ‘Add records’ and ‘Delete records’. Make sure that you are not using the Admin API Key, as Algolia doesn’t allow it to be used here.

**Reproduction**

  - Create a new Algolia API key
  - Enter the Application ID and API key in the Graphcool console
  - Click on 'Apply'
  - Error message is displayed in the notification on the right
  - The credentials form stays there and it doesn't appear as 'Enabled' when going back to 'Integrations' in the console

The above steps were suggested by this article: https://medium.com/@graphcool/algolia-auto-sync-for-graphql-backends-f78678f45889

**Comment by patrick-samy** [comment]
@marktani I think I might have found the culprit while trying to index in Algolia by creating a function in the console using this code:
https://github.com/graphcool/templates/blob/master/outdated/syncing/algolia/src/sync.js

Error in the logs:
```
{
  "code": 500,
  "error": "Error resolving named webtask",
  "details": "Error resolving named webtask: node module \"algoliasearch@3.24.6\" is not currently available"
}
```

**Comment by patrick-samy** [comment]
Might be related to this webtask issue: https://github.com/auth0/wt-cli/issues/127

**Comment by yezarela** [comment]
Same thing happened when requiring 'pubnub' on functions:
```
{
  "code": 500,
  "error": "Error resolving named webtask",
  "details": "Error resolving named webtask: node module \"pubnub@4.18.0\" is not currently available"
}
```
@patrick-samy did you find any solution for this?

**Comment by patrick-samy** [comment]
@yezarela Not for legacy console projects. I moved to a new framework project managed from the CLI.

**Comment by marktani** [comment]
@patrick-samy @yezarela the "Error resolving named webtask" error is solved, and was unrelated to the issue posted in the OP.

**Comment by marktani** [comment]
This should now work again.
