### ISSUE TITLE
how to open console on local deployment

### ISSUE THREAD

**Issue by UADACID** [graphcool/framework#1309]
whether in documentation there is how to open the console with local deploy ?

**Comment by kbrandwijk** [comment]
The console is not available in the local cluster. It's only available in the shared and private clusters.

**Comment by iamclaytonray** [comment]
Adding to @kbrandwijk, you can open the playground. It's not a feature-rich as the console, per-se, but it may be what you are looking for.

```bash
graphcool local up # starts docker
```

```bash
graphcool deploy
```

```bash
graphcool playground
```

**Comment by UADACID** [comment]
@kbrandwijk , i see, so online schema or existing schema can't be using on local cluster ?

**Comment by iamclaytonray** [comment]
You are correct, unfortunately. Hopefully you did not lose much data!
