### ISSUE TITLE
Relay Modern fragments only work, when the prop name is the same as the field name

### ISSUE THREAD

**Issue by chrish-21** [graphcool/framework#1310]
**Current behavior**
The fragment naming convention in Relay Modern states that a fragment should be named: 
`<FileName>_<propName>`, and when there is no `<propName>`, then the data prop will be used as default.

Currently the only way for me to get data into a prop, is by naming the prop the same as the GraphQL field.

This works:
`fragment FileName_user on User`

These don't work:
`fragment FileName on User` <- this should populate the prop data, containing the user.
`fragment FileName_test on User` <- this should populate the prop test, containing the user

In all 3 cases, a correct GraphQL Query is send to the server and the correct data is send back in the response. Also in all 3 cases the component receives the correct prop (user, data or test). However in the last two cases, these props will not contain the data and be null instead.

**Comment by kbrandwijk** [comment]
So if the correct request is sent to Graphcool, and the correct data is returned, how is this a Graphcool Framework issue?

**Comment by chrish-21** [comment]
You're right, the problem is probably with Relay Modern. 

I thought it was working in the Relay Modern Todo example as there's a fragment called:
`fragment TodoApp_viewer on User`, however naming the fragment TodoApp or TodoApp_test doesn't work there either.

Closing this and submitting it to the Relay repo, since as far as I understand it, that's not the intended behavior.
