### ISSUE TITLE
Unreadable MySQL Database Table Relation

### ISSUE THREAD

**Issue by radiegtya** [graphcool/framework#1317]
**Question**
In Self hosted local development, I found that table relation are unreadable. Please look image below
<img width="1271" alt="unreadable-mysql-graphcool" src="https://user-images.githubusercontent.com/2161622/33105144-5c69733c-cf5e-11e7-92cb-7a5d7b78b807.png">

Inside those table there are A & B which is connecting between two tables, but the table name is not readable. So how to read that encrypted relation table name? 

**Why I Need this?**
I need this feature because sometime I want to make myself REST API that directly access to the database, and I want it to connect to graphcool func resolver that access to my very own API.

**Expected behavior?**
I want readable table name relation

Please help, thank u

**Comment by aylabyuk** [comment]
Hi.. Graphcool newbie here..

Just wondering why is it necessary to create a separate tables for each relations? Why not just use foreign keys associated with IDs just like any rdbms normally implements?

**Comment by sorenbs** [comment]
Great question @radiegtya and sorry about the slow response :-)

The name of the relation table is determined by the id of the relation. You can see all the relations and their ids in the graphcool database in the Relation table.

Hope that helps!

**Comment by radiegtya** [comment]
thank for the response, I'll learn it later. :)
