### ISSUE TITLE
There are issues with the new service definition

### ISSUE THREAD

**Issue by Melv** [graphcool/framework#1331]
`graphcool/0.9.2 (linux-x64) node-v6.10.2`

At the moment we are migrating our legacy project to framework. We've copied our current legacy definition with

`graphcool init --copy <projectid>`

**Current behavior**

Now if we try to deploy this definition it will give the following message:

```
There are issues with the new service definition:

  Global
    ✖ [Ljava.lang.String;@4621534c (of class [Ljava.lang.String;)
```

**Reproduction**

We've traced this to some entries in the generated `permissions` section of `graphcool.yml`

example:
```
- operation: Role.read
  authenticated: true
  query: ./src/permissions/Role.graphql:read
```
By commenting out/removing  all entries containing a `query` attribute the message disappears ( another pops up but that will be another issue...)

**Expected behavior?**
No error 
Or if `query` is not valid what should it be?

**Comment by marktani** [comment]
What's the content of `./src/permissions/Role.graphql`?

**Comment by Melv** [comment]
```graphql
query read($node_id: ID) {
  SomeRoleExists(filter: {id: $node_id, team: {users_some: {id: $user_id}}})
}
```

**Comment by marktani** [comment]
It should probably say

```graphql
query read($node_id: ID!, $user_id: ID!) {
  SomeRoleExists(filter: {id: $node_id, team: {users_some: {id: $user_id}}})
}
```

**Comment by Melv** [comment]
Ah, ok I used some buckshot by commenting out all the queries. `Role.graphql` wasn't the problem. I've reduced it to exactly two queries that will trigger

```
There are issues with the new service definition:

  Global
    ✖ [Ljava.lang.String;@4621534c (of class [Ljava.lang.String;)

```

```yaml
- operation: Board.create
   authenticated: true
  query: './src/permissions/Board.graphql'
```
Content of `Board.graphql`:
```graphql
query delete($node_id: ID) {
  SomeBoardExists(filter: {AND: [{id: $node_id}, {OR: [{owner: {id: $user_id}}, {team: {owner: {id: $user_id}}}]}]})
}
query  {
  SomeUserExists(filter: {id: $user_id, teams_some: {id: $input_teamId}})
}
```

and

```yaml
- operation: Team.delete
  authenticated: true
  query: './src/permissions/Team.graphql:'
  fields: []
```

Content of `Team.graphql`:
```graphql
query update($node_id: ID) {
  SomeTeamExists(filter: {AND: [{id: $node_id}, {teamClasses_some: {OR: [{userIs: ADMIN, user: {id: $user_id}}, {userIs: SUPERADMIN, user: {id: $user_id}}]}}]})
}
query  {
  SomeTeamExists(filter: {owner: {id: $user_id}})
}
```

**Comment by kbrandwijk** [comment]
Just like `role.graphql`, these queries also miss the necessary variable declarations (`$user_id`, `$input_teamId`).

**Comment by Melv** [comment]
Thanks guys I think I can fix this manually now, I will close this and refer to this 
https://github.com/graphcool/framework/issues/1338, because those declaration are correct in our legacy project ,something goes wrong exporting these *permission queries* with `gc init --copy <projectId>`
