### ISSUE TITLE
cli error "graphcool export is not a graphcool command"

### ISSUE THREAD

**Issue by Redorb** [graphcool/framework#1335]
**Current behavior**
`▸    graphcool export --target prod`
`▸    export is not a graphcool command.`
`▸    Perhaps you meant local restart`
`▸    Run graphcool help for a list of available commands.`

**Reproduction**
Assuming you're on the latest graphcool release from npm and in a project directory:
`▸    graphcool export --target prod`

**Expected behavior?**
According to the [docs](https://www.graph.cool/docs/reference/graphcool-cli/commands-aiteerae6l/#data-workflows) I should be able to get a zip back with my production data.

Maybe the docs just need to be updated for it?

**Comment by marktani** [comment]
`graphcool export` has been removed in `0.8.0`: https://github.com/graphcool/framework/releases/tag/0.8

Please follow https://github.com/graphcool/framework/issues/1299 for updates regarding data import/export 🙂

**Comment by Redorb** [comment]
Ah alright, thanks! Want me to open up a PR to update: https://github.com/graphcool/framework/blob/master/docs/04-Reference/02-Graphcool-CLI/02-Commands.md

**Comment by marktani** [comment]
yes, that would be awesome 👍
