### ISSUE TITLE
Graphcool 1.0 - API

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#1340]
This issue documents the API surface for Graphcool 1.0

## Top level fields

For each database type, the following fields are generated:

> The type `User` is used as an example throughout this document

### Query

- `user` returns a single user
- `users` returns a list of users
- `usersConnection` returns a relay style Connection of users

> In addition to the generated query fields, the following field is present:

- `node` returns a single node by id

#### field name generation

The `user` field name is generated by taking the type name and lowercasing the first letter

The `users` and `usersConnection` field names are generated by taking the type name and lowercasing the first letter and then using the [evo-inflector library](https://github.com/atteo/evo-inflector)

### Mutation

- `createUser` create a single user
- `updateUser` update a single user
- `deleteUser` delete a single user
- `upsertUser` update a single user if exists, otherwise create
- `updateUsers` update multiple users
- `deleteUsers` delete multiple users

> Note: The API has no explicit mutations for managing relations. Instead relations are managed through nested mutations #1280 

## Details

```graphql
type Query {
  user(where: UserWhereUniqueInput): User

  users(
    where: UserWhereInput
    orderBy: UserOrderByInput
    skip: Int
    before: String
    after: String
    first: Int
    last: Int
  ): [User!]!

  usersConnection(
    where: UserWhereInput
    orderBy: UserOrderByInput
    skip: Int
    before: String
    after: String
    first: Int
    last: Int
  ): UserConnection!
}

type Mutation {
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  deleteUser(where: UserWhereUniqueInput!): User
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User

  updateUsers(data: UserUpdateInput!, where: UserWhereInput!): BatchPayload
  deleteUsers(where: UserWhereInput!): BatchPayload
}
```

See #1341 for a list of generated GraphQL types

## Nested mutations

See #1280

## Open questions

- [ ] Subscription API

**Comment by nikolasburk** [comment]
It would be helpful to have an example for a relation as well that shows how relation fields on the types are generated. For example for the following data model:

```graphql
type Post {
  id: ID! @unique
  title: String!
  author: User
}

type User {
  id: ID! @unique
  name : String!
  posts: [Post!]!
}
```

It would be interesting to see what exactly the generated model types look like and what fields they expose (especially with regards to the relation) between the types.

**Comment by SachaG** [comment]
I'd be curious to know how Prisma handles the whole user auth process: signing in, signing up, password reset, etc. Or is that handled outside of the GraphQL API somehow?
