### ISSUE TITLE
Graphcool 1.0: Generated type names

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1341]
## Introduction
This spec contains two sections:

**Overview** contains a list of all generated types
**Details** explains where each type is used

### Examples

All examples assume a `User` type

### Conflicts

To avoid type name conflicts, it is not allowed to create types with the same name as one of the generated types listed in this document.

> We considered changing the name of a generated type when a conflicting model was introduced. We decided against this as this represents a breaking change to the API, and such a change should not be introduced without explicit action by the developer.

# Overview

## The naming scheme for Nested Mutation Types
Input types for wrapper types for nested mutations are following this naming pattern:
`[Entity][Operation][Arity]Without[RelationFieldName]Input`
The actual types used to create the entity are named:
`[Entity][Operation]Without[RelationFieldName]Input`
e.g.
```graphql
input UserCreateOneWithoutFriendsInput {
  create: UserCreateWithoutFriendsInput
}
input UserCreateManyWithoutFriendsInput {
  create: [UserCreateWithoutFriendsInput!]
}
```

### Create

`UserCreateInput`

`UserCreateOneInput`
`UserCreateManyInput`

> sub fields `create` and `connect` use types `UserCreateInput` and `UserWhereUniqueInput` respectively

> Note: The `OneInput` and `ManyInput` types are introduced by #1280

### Update

`UserWhereUniqueInput`
`UserUpdateInput`

`UserUpdateOneInput`
`UserUpdateManyInput`
`UserUpdateWithTodoesInput`

> sub fields `create` and `upsert.create` use type `UserCreateInput`.
> sub fields `update` and upsert.update use type `UserUpdateWithoutTodoesDataInput`
> sub field `connect` use type `UserWhereUniqueInput`

> In `UserUpdateManyInput` the sub fields `update.by`, `upsert.by`, `disconnect`, `delete` use the type `UserWhereUniqueInput`

### Delete

`UserWhereUniqueInput`

### user query

`UserWhereUniqueInput`

### Users and UsersConnection Query

`UserWhereInput`
`UserOrderByInput`

## Types

`User`
`UserConnection`
`UserEdge`

`UserAggregate`
`UserAggregateResult`

`UserGroupBy`
`UserGroupByResult`

> Note: The aggregate and groupBy types are introduced by #1312 

# Details

For each type we include a code block with 3 sections:

```
A GraphQL type definition that uses comments to describe how it is generated

A partial query or mutation that shows where the type is used

A partial query or mutation with example values
```

#### UserCreateInput

```graphql
input UserCreateInput {
  # all scalar fields. Required fields are required, optional fields are not.
  # all relation fields. The type is a nested mutation as appropriate for the relation
}

mutation { createUser(data: UserCreateInput): User}

mutation { createUser(data: {name: "My Name"}) {name}}
```

#### UserCreateOneInput

```graphql
input UserCreateOneInput {
  create: UserCreateInput
  connect: UserWhereUniqueInput
}

mutation { createUser(data: {bestFriend: UserCreateOneInput}): User}

mutation { createUser(data: {bestFriend: {create: {name: "Karl Karlson"}}}) {name}}
```

#### UserCreateManyInput

```graphql
input UserCreateManyInput {
  create: [UserCreateInput!]
  connect: [UserWhereUniqueInput!]
}

mutation { createUser(data: {friends: UserCreateManyInput}): User}

mutation { createUser(data: {friends: {create: [{name: "Karl Karlson"}]}}) {name}}
```

#### UserWhereUniqueInput

```graphql
input UserWhereUniqueInput {
  # all unique fields
}

mutation { updateUser(where: UserWhereUniqueInput, data: UserUpdateInput): User}

mutation { updateUser(where: {id: "some-id"}, data: {name: "Karl Karlson"}) {name}}
```

#### UserUpdateInput

```graphql
input UserUpdateInput {
  # all scalar fields. All fields are optional.
  # all relation fields. The type is a nested mutation as appropriate for the relation
}

mutation { updateUser(where: UserWhereUniqueInput, data: UserUpdateInput): User}

mutation { updateUser(where: {id: "some-id"}, data: {name: "My Name"}) {name}}
```

#### UserUpdateOneInput

```graphql
input UserUpdateOneInput {
  create: UserCreateWithoutTodoesInput
  connect: UserWhereUniqueInput
  update: UserUpdateWithoutTodoesInput
  upsert: UserUpsertWithoutTodoesInput
  delete: Boolean
  disconnect: Boolean
}

mutation { updateUser(where: UserWhereUniqueInput, data: {bestFriend: UserUpdateOneInput}): User}

mutation { updateUser(where: {id: "some-id"}, data: {bestFriend: {create: {name: "Karlson"}}}) {name}}
```

#### UserUpdateManyInput

```graphql
input UserUpdateManyInput {
  create: [UserCreateWithoutTodoesInput!]
  connect: [UserWhereUniqueInput!]
  update: [UserUpdateWithoutTodoesInput]
  upsert: UserUpsertWithWhereUniqueInput
  delete: Boolean
  disconnect: Boolean
}

mutation { updateUser(where: UserWhereUniqueInput, data: {friends: UserUpdateManyInput}): User}

mutation { updateUser(where: {id: "some-id"}, data: {friends: {create: [{name: "Karlson"}]}}) {name}}
```

#### UserUpdateWithWhereUniqueInput

```graphql
input UserUpdateWithWhereUniqueInput {
  where: UserWhereUniqueInput!
  data: UserUpdateInput!
}

mutation { updateUser(where: UserWhereUniqueInput, data: {friends: {update: [UserUpdateWithWhereUniqueInput!]}}): User}

mutation { updateUser(where: {id: "some-id"}, data: {friends: {update: [{where:{name: "Åge"}, data: {name: "Karlson"}}}) {name}}
```

#### UserUpsertInput

```graphql
input UserUpsertInput {
  create: UserCreateInput!
  update: UserUpdateInput!
}

mutation { updateUser(where: UserWhereUniqueInput, data: {bestFriend: {upsert: UserUpsertInput}}): User}

mutation { updateUser(where: {id: "some-id"}, data: {bestFriend: {upsert: {update: {name: "Karlson"}, create: {name: "Karlson"}}}) {name}}
```

#### UserUpsertWithWhereUniqueInput

```graphql
input UserUpsertWithWhereUniqueInput {
  where: UserWhereUniqueInput!
  create: UserCreateInput!
  update: UserUpdateInput!
}

mutation { updateUser(where: UserWhereUniqueInput, data: {friends: {upsert: [UserUpsertWithWhereUniqueInput!]}}): User}

mutation { updateUser(where: {id: "some-id"}, data: {friends: {upsert: [{where:{name: "Åge"}, update: {name: "Karlson"}, create: {name: "Karlson"}}}) {name}}
```

### Upsert

```graphql
mutation { upsertUser(where: UserWhereUniqueInput, create: UserCreateInput!, update: UserUpdateInput): User}

mutation { upsertUser(where: {id: "some-id"}, create: {age: 55, name: "Karl Karlson"}, update: {name: "Karl Karlson"}) {name}}
```

#### UserWhereUniqueInput

```graphql
mutation { deleteUser(where: UserWhereUniqueInput): User}

mutation { deleteUser(where: {id: "some-id"}) {name}}
```

#### UserWhereUniqueInput

```graphql
query { user(where: UserWhereUniqueInput): User}

query { user(where: {id: "some-id"}) {name}}
```

#### UserWhereInput

```graphql
input UserWhereInput {
  # same as existing filter
  # todo: spec this out
}

type Query {
   users(filter: UserWhereInput): [User!]!
}

query { user(filter: {name_contains: "Karl"}) {name}}
```

#### UserOrderByInput

```graphql
enum UserOrderByInput {
  # ascending and descending for all non-list scalar fields
}

query { users(orderBy: UserOrderByInput): [User!]}

query { users(orderBy: NAME_ASC) {name}}
```

#### User

```graphql
type User {
  # all scalar fields
  # all relation fields
}

query { user(where: UserBy): User}

query { user(where: {name: "Karlson"}) {name}}
```

#### UserEdge

```graphql
type UserConnection {
  edges: [UserEdge!]
  aggregate: UserAggregate
  groupwhere: UserGroupBy
}

type UserEdge {
  node: User!
}

query { usersConnection: UserConnection}
query { usersConnection: {edges: [UserEdge!]}}

query { usersConnection {edges{node{name}}}}
```

> todo: specify aggregate types

`UserAggregate`
`UserAggregateResult`

`UserGroupBy`
`UserGroupByResult`

## Missing

- [ ] Subscription types
- [ ] Upsert

## Open questions

- [ ] Does this make sense in the context of schema binding?

**Comment by marktani** [comment]
Did you consider optional vs required for all input fields?

For example 

`mutation { deleteUser(where: UserWhereUniqueInput): User}`
vs
`mutation { deleteUser(where: UserWhereUniqueInput!): User!}`

**Comment by marktani** [comment]
in 

```graphql
type User {
  # all scalar fields
  # all relation fields
}
```

what's the type of relational fields, including input arguments, for `to-one` and `to-many`?

For example, with this schema:

```graphql
type User @model {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  title: String!
  post: Post! @relation(name: "A")
}

type Post @model {
  id: ID! @isUnique
  title: String
  user: User! @relation(name: "A")
}
```

`post` currently has this shape

![image](https://user-images.githubusercontent.com/1780597/33761002-ede98eb8-dc07-11e7-98e1-88d0fc4ee187.png)

Using `post(filter: PostFilter): Post` instead would be better, because with the filter the field might return `null`, resulting in a `Cannot return null for non-nullable type` error.

**Comment by sorenbs** [comment]
We should consider always returning a Payload type for mutations that wrap the actual response. This will allow us to add extra information in the future.

Once simple example where we might want to do that is the upsert mutation:

```graphql
mutation { upsertUser(where: UserWhereUniqueInput, create: UserCreateInput!, update: UserUpdateInput): User}
```

In the future we might want to also return information about whether a new User was created or an existing user was updated.

**Comment by sorenbs** [comment]
We need to make a decision for nested mutations. It is a tradeoff between:

- Generate multiple input types for nested mutations, and accept more bloat in the database schema
- Generate only a single Input type, but performing more runtime checks

The following mutation is not valid as it would create two `Todo`s, one `Comment` and link both `Todos` to the `Comment`s todo field (which is not a list):

```graphql
mutation { createTodo(
  data: {
    title: "My Todo for today"
    comments: {
      create: [ {text: "This is a great idea!", todo: {create: {...}} } ,{text: "...!"} ]
    }
  })
}
```

We can solve this by 

1. Create a specific input type for the case when a `Comment` is created in a nested mutation that originates at the `comments` field on `Todo`. This is what we currently do. The downside is that we generate a lot of input types.

2. Check this at runtime and return an error for invalid queries. The downside of this is that auto-complete in GraphiQL becomes less useful.

This might also have implications for future tooling that automatically generates type definitions based on the introspection query, but I do not have enough insight into this topic to weigh the pros and cons.

Would love input from @schickling @marktani and @kbrandwijk on this one.

**Comment by marktani** [comment]
My thoughts:

* > The downside is that we generate a lot of input types.
  
  More input types means a bigger schema, which has impact on performance, but as the schema is mostly cached, this only affects tooling and can be seen as a _one time cost at build time_. Is there another consequence of this?

* > The downside of this is that auto-complete in GraphiQL becomes less useful.
  
  In this case, all nested input objects are optional all the time and it's up to the developer to
    
  * don't specify an inner nested input field that was used in the outer layer (`todo` in this case)
  * always specify all inner nested input fields that stem from required relations (and are not used in the outer later)

  This results in a _repeating cost at development time by increasing the required mental overhead_.

---

I tend to prefer the first alternative.

**Comment by sorenbs** [comment]
I agree with @marktani. I think having required relation fields be required in the input types is important enough to warrant the extra types.

I did not consider this before. i will add a section to the spec about naming context aware input types for nested mutations

**Comment by marktani** [comment]
This feature is now available as part of **stage beta2** of [the developer preview for Graphcool 1.0](https://github.com/graphcool/framework/pull/1318#issuecomment-353674448).

**Comment by schickling** [comment]
@sorenbs @mavilein what about upsert & subscription types?

**Comment by steebchen** [comment]
I honestly think the orderBy types are super ugly: `orderBy: NAME_ASC`.

Why are they not generated with enums so we could write `orderBy: { field: NAME, direction: ASC }`? This would also make re-using the possible fields a lot easier.
