### ISSUE TITLE
Define the model layer's validation rules while defining the schema

### ISSUE THREAD

**Issue by levioza** [graphcool/framework#1346]
Feature Request
============
It would be great if there's a better approach to define the model layer's validation rules than relying entirely on hook functions. I believe that you could adopt an API similar to the Hibernate Validator (Java Persistence API).

For example:
```
type Customer @model {
  id: ID! @isUnique
  userName: String! @isRequired @maxLength(15)
  email: String! @regex('/^[^\s@]+@[^\s@]+\.[^\s@]+$/')
}
```
I believe that it might be possible to implement such decorators with a library like Joi https://github.com/hapijs/joi.

**Comment by marktani** [comment]
Thanks for the suggestion! There is already a mature proposal about specifying constraints exactly as you suggested here: https://github.com/graphcool/framework/issues/728

Would love to hear your feedback there 🙂
