### ISSUE TITLE
Cassandra Database backend support

### ISSUE THREAD

**Issue by lowsky** [graphcool/framework#1353]
For having a very powerful, scalable backend, can we have [Apache Cassandra](http://cassandra.apache.org/) support?

This is interesting, when you need a real scalable database which is also fault tolerant.

There is this powerful [Cassandra Query Language](http://cassandra.apache.org/doc/latest/cql/index.html) which support all the usual table oriented commands,
for access by java there is e.g. this [jdbc driver](https://github.com/adejanovski/cassandra-jdbc-wrapper)

**Comment by kbrandwijk** [comment]
@lowsky There's an existing issue for supporting different database platforms: https://github.com/graphcool/framework/issues/1006 Maybe you can add this option there too?

**Comment by lowsky** [comment]
Thanks, I will add it there
