### ISSUE TITLE
Getting error after executing a mutation -> "code": 4011, “message”: “Something unexpected happened in an Action: ’Query does not pass validation.

### ISSUE THREAD

**Issue by shiang** [graphcool/framework#1357]
**Current behavior**
Running mutation (such as create or update) on a certain type gets me the following error message:

>“code”: 4011,
“message”: “Something unexpected happened in an Action: ’Query does not pass validation. Violations:\n\nCannot query field ‘subOrderInfoes’ on type ‘SubOrder’. (line 14, column 7):\n      subOrderInfoes {\n      ^\n\nCannot query field ‘order’ on type ‘SubOrder’. (line 22, column 7):\n      order {\n      ^' - ‘’“,

**Reproduction**

This happened after I removed the "subOrderInfoes" and "order" fields on the "SubOrder" type from the console (I am still on legacy project).

I also made sure there was no data on those two fields before deleting them from the schema.

However I see the mutation would run successfully as I can see the data being created (updated) from the console.

**Expected behavior?**

**Comment by marktani** [comment]
You probably still refer to the old fields from an Algolia index query.

**Comment by shiang** [comment]
😅 You are right. I forgot to update the query in Algolia index which I was testing few months ago. Thanks for the help!
