### ISSUE TITLE
GraphQL Database Schema Generation

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1361]
It's a very common scenario to re-fetch the generated database schema (which is used for the GraphQL server application) after deploying a service. To make this workflow easier the CLI should automatically refresh the database schema file after each successful deploy.

## File Path

There are multiple ways how the CLI knows about where the database schema file is stored:

1. Schema file path can be specified via the `schema` property in the `graphcool.yml`
2. If no `schema` property is specified but a graphql-config file is found which contains a project with either the key `graphcool`, `database` or `db`, it's `schemaPath` is used.
3. If none of the above apply no schema file is created or updated.

## Schema generation

The database schema file should be generated using the following structure (see #1341 for type names):

1. Model types
2. Enum types
3. Query type
4. Mutation type
5. Subscription type
6. Connection & edge types
7. Aggregate types
8. GroupBy types
9. Input types
10. Where types

**Comment by marktani** [comment]
This has been implemented in the latest developer preview of Graphcool 1.0. Check https://github.com/graphql-boilerplates/node-graphql-server for an example.
