### ISSUE TITLE
Pusher Push Notifications Broken

### ISSUE THREAD

**Issue by ylac** [graphcool/framework#1363]
**Current behavior**
Running the pushNotification mutation as per the Pusher template does not trigger a push notification. It also returns an error if pusher.notify is called with a callback argument (pusher.trigger creates a normal Pusher message as per https://github.com/pusher/pusher-http-node, and works fine). 

The error looks like:

`[
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "pushNotification"
      ],
      "code": 2063,
      "message": "The payloadType for the resolver `pushNotification` is not nullable, but the resolver returned null.",
      "requestId": "us-west-2:simple:[redacted]"
    }
  ]`

My call of pusher.notify looks like:

```
const notifPromise = new Promise((resolve, reject) => {
    pusher.notify(
        pusherChannels,
        data,
        (error, req, res) => {
          console.log(`pusher.notify req: ${JSON.stringify(req)}`)
          if (error) {
            console.log(`pusher.notify error: ${JSON.stringify(error)}`)
            return {
              error: 'pusher.trigger error'
            }
          } else {
            console.log(`pusher.notify res: ${JSON.stringify(res)}`)
            resolve(res)
          }
        }
      )
    })
```

and I'm initialising the Pusher object with parameter `host: 'nativepush-cluster1.pusher.com'` as per the server API linked above.

Running pusher.notify outside of a promise doesn't help, nor does making pushNotification synchronous.

**Reproduction**
Using deployed graphcool on shared-us-west-2 with graphcool@0.9.2/0.10.1 and Windows 7 x64. Trying to receive push notifications on a react-native app.

**Comment by marktani** [comment]
The error message 

> The payloadType for the resolver pushNotificationis not nullable, but the resolver returned null.

means that you declared a _required_ payload, but your function returns `null`. From your question, it's not clear if it's intended to return null or not. If it's intended, please make the payload non-required. If it's not intended, share your complete function so we can find out why `null` is returned.

**Comment by ylac** [comment]
Turns out the issue was that the icon field in the fcm.notification object is necessary.
