### ISSUE TITLE
how to add id in othe schema relation

### ISSUE THREAD

**Issue by nareshvarun** [graphcool/framework#1372]
mutation{
  createUserDetails(
   firstName:"naveen"
    secondName:"ramesh"
    mobileNum:"95538719489"
    email:"naregjyhgh.g@stellentsoft.com"
    password:"123456"
  
    cities:[
      {
      id:"cjakni4db45on0130fk249eko"
      }
    ]){
    id
    firstName
    secondName
    mobileNum
    email
    password
    
    citieses{
      id
    }
    }
}

**Comment by marktani** [comment]
Hey @nareshvarun, I'm not quite sure what you mean with this. I believe your use case is covered in the improve nested mutation API: https://github.com/graphcool/framework/issues/1280. Would love to hear your feedback there! 🙌
