### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by Toosick** [graphcool/framework#1411]
We have a resource with 39k rows and 25 fields. We are trying to just add 1 field and hitting an error. Is this a bug or something else needs to be done? Commenting out the field works, uncommenting out the field hits this error every time. We were able to run this on our other development project that has 8k rows (the only difference in the schema is this 1 field added)

**Field to add:**
`chromatogramUrl: String`

**Version:**
`graphcool/0.9.2 (windows-x64) node-v6.10.2`

**Error:**
```
Bundling functions... 7.8s
Deploying to shared-us-west-2 with target prod... !

ERROR: Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: eu-west-1:system:cjbce5hkn182f0123uew44bna

{
  "data": {
    "push": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: eu-west-1:system:cjbce5hkn182f0123uew44bna",
      "requestId": "eu-west-1:system:cjbce5hkn182f0123uew44bna",
      "path": [
        "push"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ]
    }
  ],
  "status": 200
}

**Comment by marktani** [comment]
This is now resolved.

**Comment by jainvinit** [comment]
we are hitting the same issue. how to fix this?

**Comment by marktani** [comment]
Please reach out to support@graph.cool :slightly_smiling_face:

**Comment by jainvinit** [comment]
i did but no response :(
