### ISSUE TITLE
Cannot interactively deploy without local cluster

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#1421]
If my local cluster is not running, and I have a project with the default cluster set to 'local', I cannot interactively deploy:
```
λ graphcool deploy -i
 !    Could not find cluster 'local', which is used in stage 'default'.
```

graphcool/1.0.4-alpha.8 (windows-x64) node-v9.0.0

**Comment by sorenbs** [comment]
This is now fixed in the latest beta 🎉

**Comment by kbrandwijk** [comment]
That was fast! Tested and confirmed with graphcool@1.0.0-alpha1.2.2 (no I don't understand numbering either 🙈)
