### ISSUE TITLE
Only execute command if CLI and cluster versions match up

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#1423]
The major & minor version of the CLI and cluster need to match in order to run `gc deploy`. Otherwise there is a error message to either upgrade the CLI or the cluster (via `gc upgrade [version]`).

The version should be checked **by the CLI** for any command related to clusters.

**Comment by schickling** [comment]
I suggest to following condition:

The major & minor version of the CLI and cluster need to match in order to run `gc delopy`. Otherwise there is a error message to either upgrade the CLI or the cluster (via `gc upgrade [version]`)
