### ISSUE TITLE
The project created by cli 2.1.0 beta doesn't work

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1424]
_From @state0fmind on December 20, 2017 7:14_

`(node:938) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [ERROR] in /Users/state0fmind/Projects/GitHub/blogr/graphcool.yml: Errors while validating graphcool.yml:
  data should have required property 'stages'`

`(node:938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

_Copied from original issue: graphql-cli/graphql-cli#71_

**Comment by state0fmind** [comment]
Do the graphcool framework have any external dependency except the npm installation? What I don't understand is how does it create a graphql database(which is sql based) if I don't have sql installed and also graphcool doesn't have it as an dependency. If you could explain this over a medium post more clearly, that'd help a lot. Thanks

**Comment by bkniffler** [comment]
@state0fmind I think the CLI will leverage docker to create containers that contain MySQL database for local dev. Here is the docker-compose.yml file:

https://github.com/graphcool/framework/blob/master/cli/packages/graphcool-cli-core/src/commands/local/docker/docker-compose.yml

**Comment by marktani** [comment]
This should be fixed now.
Please create another issue if you have more questions 🙂

**Comment by state0fmind** [comment]
Yep it's fixed, should have closed myself.
