### ISSUE TITLE
A Tutorial for the beta version

### ISSUE THREAD

**Issue by state0fmind** [graphcool/framework#1438]
**What feature are you missing?**
A Tutorial for the beta version

**How could this feature look like in detail? Tradeoffs?**
Would love to have a single page description about how graphcool deploy works in the projects created by the cli. How do I deploy it locally or on a private server. 

https://github.com/graphcool/framework/issues/1424

**Comment by marktani** [comment]
Hey @state0fmind, thanks for your feedback! Did you already check out some of the boilerplates for Graphcool 1.0?

Here's a good starting point [for Node](https://github.com/graphql-boilerplates/node-graphql-server/tree/master/advanced) and [for TypeScript](https://github.com/graphql-boilerplates/typescript-graphql-server). 🙂 

If you have a question about getting started with the boilerplates, please post it in the respective repository. Thanks!

**Comment by state0fmind** [comment]
@marktani are these the same boilerplates the graphql-cli uses?

**Comment by marktani** [comment]
Yes, they are.
