### ISSUE TITLE
Command to generate valid service token

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#1440]
> I think it would be super helpful for local workflows to let the CLI generate a JWT token for a specific service/stage.

The `graphql-config` extension already handles this for you in combination with the Playground, but  this command would still be super useful for various reasons:

* increases visibility for what is going on under the hood
* useful for CI workflows

The command could be called `graphcool db-token` and accept a `--stage` parameter.

**Comment by nikolasburk** [comment]
I'm also in favor of this, just instructing people to run a single CLI command instead of [this](https://github.com/graphql-boilerplates/react-native-graphql/blob/master/apollo-client/basic/README.md#im-getting-a-schema-could-not-be-fetched-error-after-deploying-what-gives) would be so much better.

**Comment by schickling** [comment]
A couple of thoughts:

1. In case there are multiple secrets specified, I suggest to always use the first secret.
2. I'd suggest making this somehow part of the `gc info` command. The `info` command should also provide a way to only print the URL endpoint similar to [`apex/up`](https://up.docs.apex.sh/#getting_started)

**Comment by marktani** [comment]
This is now part of the latest proposal in #1330.
