### ISSUE TITLE
Deployment results in 500 error

### ISSUE THREAD

**Issue by reinvanimschoot** [graphcool/framework#1445]
**Current behavior**

When I try to use `graphcool deploy`, this results in the following error:

```
ERROR: GraphQL Error (Code: 500)

{
  "requestId": "api:api:cjbhljsak0iyb01139r5888bb",
  "error": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: api:api:cjbhljsak0iyb01139r5888bb",
  "status": 500
}
```

**Reproduction**

Too be sure, I created a new boilerplate folder and tried to deploy there but I got the same result. So I don't believe it's a matter of my specific project.

**Expected behavior?**
That I can deploy my changes and continue working.

**Comment by marktani** [comment]
Looks like you are trying to deploy to a project that does not exist, what's the content of your `graphcool.yml`? 🙂

**Comment by reinvanimschoot** [comment]
Where should I add that project then? Because I just updated to the latest beta, did a new `graphql create` but now I'm getting the following error:

```
ERROR: No service with name 'beta-server' and stage 'dev' found
```

**Comment by marktani** [comment]
Which choice did you pick for `graphql create`?
What's the content of your graphcool.yml? 🙂

**Comment by reinvanimschoot** [comment]
The name is dondat-server but I get the error with all boilerplates I try to deploy.  

The content of my graphcool.yml is the following:

```
service: dondat-server

datamodel: database/datamodel.graphql

secret: mysecret123
```

**Comment by marktani** [comment]
I can deploy just fine following these steps:

* `npm install -g graphql-cli graphcool@beta`
* `graphql create my-project`
* `cd my-project`
* `graphcool deploy`

What are the steps to reproduce your error on your machine?

**Comment by marktani** [comment]
What's the output of `cat ~/.graphcool/cache.yml`? 🙂

**Comment by reinvanimschoot** [comment]
I tried it one more time with another fresh boilerplate and it seems to work now. Strange :) but thanks for the help in any case!
