### ISSUE TITLE
npm install -g graphcool does not work on windows with latest release

### ISSUE THREAD

**Issue by KevinAsher** [graphcool/framework#1451]
After running `npm install -g graphcool `, when i try to run `gcf`, i get the following message:
```

 !    'ENOENT': ENOENT: no such file or directory, lstat 'C:\Users\Administrador\.graphcool'

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

The previous version `0.10.1` seems to work ok.

**Comment by ekrolewicz6** [comment]
got the same issue here with npm install -g graphcool AND npm install -g graphcool-framework...

**Comment by melxx001** [comment]
I get the same error on a Mac too. 

```
▸    'ENOENT': ENOENT: no such file or directory, lstat '/Users/melxx001/.graphcool'

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

**Comment by ilumin** [comment]
workaround, create a folder it want `$ mkdir ~/.graphcool`
but some option from previous version will not work, such as `--schema` or `--name` :(

**Comment by state0fmind** [comment]
@ilumin can verify that's the workaround, did same to make the example projects work.

**Comment by sw-yx** [comment]
can verify that this is not just on windows. what happened? :(

**Comment by jasonrhodes** [comment]
Confirm this happens on Mac as well, I did
```sh
npm install -g graphcool@0.10
```
and then `graphcool init` worked without this error.

Should be the same for `graphcool-framework`

**Comment by MohammedSiddiqui10p** [comment]
Facing this issue on Ubuntu as well.

**Comment by FredyC** [comment]
I took a peek into source files, the error is happening inside `graphcool-cli-engine` which isn't open sourced apparently. However, there is this piece of code in the installed module...

```
    Environment.prototype.migrateGlobalFiles = function () {
        var dotFilePath = path.join(this.config.home, '.graphcool');
        var dotExists = fs_1.default.pathExistsSync(dotFilePath);
        if (fs_1.default.lstatSync(dotFilePath).isDirectory()) {
            return;
        }
        var rcHomePath = path.join(this.config.home, '.graphcoolrc');
        var rcHomeExists = fs_1.default.pathExistsSync(rcHomePath);
        var dotFile = dotExists ? fs_1.default.readFileSync(dotFilePath, 'utf-8') : null;
        var rcFile = rcHomeExists ? fs_1.default.readFileSync(rcHomePath, 'utf-8') : null;
        // if both legacy files exist, prefer the newer one, .graphcool
        if (rcHomeExists && rcFile) {
            // only move this file, if it is json and contains the "token" field
            // in this case, it's the old format
            ....
        }
```
I haven't used graphcool now for like 2 months, so I am not sure why all this shifting and what's actually happening. Apparently creating empty `.graphcool` directory indeed is a valid workaround as it then returns on a first condition and nothing else is being done. I wasn't able when and how is this directory used.

**Comment by marktani** [comment]
Can everyone confirm that running `$ mkdir ~/.graphcool` fixes this problem? @KevinAsher @ekrolewicz6 @melxx001 @sw-yx @jasonrhodes @MohammedSiddiqui10p

---

@ilumin:

> but some option from previous version will not work, such as --schema or --name :(

This change was actually introduced a long time ago, with the introduction of `graphcool.yml` where you now reference the datamodel schema.

---

@FredyC:

> I haven't used graphcool now for like 2 months, so I am not sure why all this shifting and what's actually happening.

The binary name change is in anticipation of Graphcool 1.0, [as mentioned in the release notes](https://github.com/graphcool/framework/releases/tag/0.11.4). You can find out more about the Graphcool 1.0 preview [in the feedback thread in the Forum](https://www.graph.cool/forum/t/developer-preview-graphcool-1-0-beta/1891?u=nilan).

> the error is happening inside graphcool-cli-engine which isn't open sourced apparently.

[It is](https://github.com/graphcool/framework/tree/master/cli/packages/graphcool-cli-engine).

**Comment by FredyC** [comment]
Ok, thanks. I made the fix ... #1459

**Comment by sw-yx** [comment]
@marktani confirmed. seems an unfortunate oversight but an easy fix.

**Comment by MohammedSiddiqui10p** [comment]
@marktani also confirming. I tried the workaround suggested by @state0fmind and it ran perfectly afterwards

**Comment by jonasdumas** [comment]
Thanks, @marktani 
mkdir ~/.graphcool
solve the problem
