### ISSUE TITLE
How to develop locally 

### ISSUE THREAD

**Issue by kdichev** [graphcool/framework#1453]
Hey, im pretty new to docker and stuff like that and I am trying to develop my functions locally.
Is there a way to do local dev at all?

Best case scenario is that I could dev and debug my functions locally and when they are ready to deploy to the cloud and right now i am developing and debugging after graphcool deploy and this takes a lot of time and development moves very slowly

**Comment by state0fmind** [comment]
Docs - https://www.graph.cool/docs/1.0/quickstart/backend/node/node-phe8vai1oo

**Comment by kdichev** [comment]
I guess this only for 1.0?

**Comment by state0fmind** [comment]
https://www.graph.cool/docs/0.x/quickstart/backend/node/node-phe8vai1oo

**Comment by kdichev** [comment]
This is what I was searching for!

Now I can access local playground which is amazing.

Unfortunatelly it is not working I get this error when I enter local playground

`Schema could not be fetched.
Please check if the endpoint 'http://localhost:60000/simple/v1/cjba2txd62g5p0182pezwuy1z' is a valid GraphQL Endpoint.`

and when I click on play button:

`
{
  "code": 3016,
  "requestId": "local:simple:cjbnn68ba000x0127qfkrg99r",
  "error": "Project not found: 'cjba2txd62g5p0182pezwuy1z'"
}
`

I suspect this is because my `.graphcoolrc` is not updated with the clusters after ir run `graphcool local up`

**Comment by kdichev** [comment]
I have managed to get my schema to local cluster by using `gc deploy --interactive` and set up the local server.

Schema is now available in local playground but there is no data
