### ISSUE TITLE
Mutation creates duplicates always

### ISSUE THREAD

**Issue by state0fmind** [graphcool/framework#1454]
**Current behavior**
Mutation creates duplicates always.

**Reproduction**
> Repo - https://github.com/state0fmind/refract

**Expected behavior?**
createpost/create user shouldn't create duplicates.

> duplicate https://github.com/graphql-boilerplates/node-graphql-server/issues/59

**Comment by state0fmind** [comment]
> duplicate https://github.com/graphql-boilerplates/node-graphql-server/issues/59

**Comment by marktani** [comment]
Closing as duplicate of graphql-boilerplates/node-graphql-server#59.
