### ISSUE TITLE
DB issue while trying to deploy local cluster

### ISSUE THREAD

**Issue by matthieumasse** [graphcool/framework#1491]
Hi there,

I'm facing an issue while trying to deploy local cluster (using documentation).

**Current behavior**
It seems that mysql container is not ok :
First time, the "local up" function looped on "Waiting for Graphcool to initialize. This can take several minutes..."
===> docker logs from graphcool-dev : "unable to connect to mysql"

Then i stopped and removed containers, purged my old images and try again.

Now, docker logs from db container :
```
[Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
[ERROR] --initialize specified but the data directory has files in it. Aborting.
```
Thanks in advance for your help.

**Comment by marktani** [comment]
Could you share the output of the following commands? 🙂 

```sh
graphcool version
docker ps
docker -v
docker-compose -v
docker-machine -v
```

Thanks!

**Comment by matthieumasse** [comment]
graphcool-framework/0.11.4 (linux-x64) node-v8.9.4
Docker version 1.13.1, build 092cba3
docker-compose version 1.18.0, build 8dd22a9

No docker machine on my laptop.
Is it mandatory? Because not in documentation.


 IMAGE                            COMMAND                  CREATED             STATUS                         PORTS                     
graphcool/graphcool-dev:0.11.1   "/app/bin/single-s..."   15 seconds ago      Up 2 seconds                   0.0.0.0:60000->60000/tcp   local_graphcool_1
mysql:5.7                        "docker-entrypoint..."   16 seconds ago      Restarting (1) 3 seconds ago                              local_graphcool-db_1
graphcool/localfaas:0.11.1       "/app/bin/localfaas"     16 seconds ago      Up 14 seconds                  0.0.0.0:60050->60050/tcp   local_localfaas_1

**Comment by marktani** [comment]
It looks like the `mysql` container is in a restart loop, could you try shutting that down?
You can run 
```
graphcool local stop
graphcool local up
```

**Comment by matthieumasse** [comment]
Same result.
`Initializing database
2018-01-03T15:46:47.206898Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-01-03T15:46:47.209320Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2018-01-03T15:46:47.209401Z 0 [ERROR] Aborting
`

(And i installed docker-machine : ```docker-machine version 0.13.0, build 9ba6da9```)

**Comment by marktani** [comment]
I noticed both your `docker` version is quite old, here's mine:

```
Docker version 17.09.1-ce, build 19e2cf6
```

**Comment by matthieumasse** [comment]
I just reinstalled docker, rm containers and tried again.
Same result.

`Docker version 17.12.0-ce, build c97c6d6`

**Comment by marktani** [comment]
Is the status of `mysql` container still "Restarting"?

**Comment by matthieumasse** [comment]
yes. I guess due to `[ERROR] --initialize specified but the data directory has files in it. Aborting.`

But i don't know where to find and delete the files. (probably defined in graphcool-framework compose file.

**Comment by sorenbs** [comment]
@matthieumasse The local database is using a docker volume for its data directory. You can list all volumes like this:

```
❯ docker volume ls
DRIVER              VOLUME NAME
local               localdatabase_db-persistence
```

stopping and removing the mysql docker image, then removing the volume should clear up any data inconsistencies.

**Comment by matthieumasse** [comment]
Perfect. Thanks a lot.
