### ISSUE TITLE
FAQ links not working

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#1509]
https://www.graph.cool/docs/faq/

![image](https://user-images.githubusercontent.com/1780597/34581551-25a4b582-f191-11e7-95d9-7f27eb55beec.png)

![image](https://user-images.githubusercontent.com/1780597/34581555-2aeac09a-f191-11e7-9d2c-84d2fecc0d09.png)

**Comment by williamli** [comment]
There is an extra "undefined" in the URL path. Removing the /undefined fixes this issue.

What it is now
https://www.graph.cool/docs/undefined/faq/basic-iph5dieph9/#is-graphcool-a-web-framework,-similar-to-ruby-on-rails-or-express.js

What it SHOULD BE
https://www.graph.cool/docs/faq/basic-iph5dieph9/#is-graphcool-a-web-framework,-similar-to-ruby-on-rails-or-express.js

**Comment by timsuchanek** [comment]
A fix is deploying :)
