### ISSUE TITLE
Group relation

### ISSUE THREAD

**Issue by gustavopch** [graphcool/framework#217]
Suppose we have Product type and we created the objects:
`Product1 (id: 0001, name: Margherita Pizza, price: 13)`
`Product2 (id: 0002, name: Margherita Pizza, price: 14.5)`
`Product3 (id: 0003, name: Margherita Pizza, price: 15)`

I want to be able to make the following query...

    {
      Product(id: 0001) {
        versions {
          name
        }
      }
    }

...and get as result the three objects that I listed.

That would be a sort of a "group relation". Initially, each object will have a reference to itself in the `versions` field. Then I would connect Product1 and Product 2. Now, the `versions` field of each object would have a reference to itself and the other one. Then I would connect Product 2 and Product 3 (or Product 1 and 3). Now, the `versions` field of each object would have a reference to itself and to each of the other two.

I know we can currently achieve this using two different types like:

    type Product {
      id: ID!
      name: String!
      price: Float!
      versionsGroup: ProductVersions! @relation(name: "ProductVersions")
    }

    type ProductVersionsGroup {
      id: ID!
      versions: [Product!]! @relation(name: "ProductVersions")
    }

But I think my proposal is cleaner because it doesn't require keeping that second object and the query doesn't require traversing 2 steps like the following:

    {
      Product(id: 0001) {
        versionsGroup {
          versions {
            name
          }
        }
      }
    }

Is this something too specific to my use case? If yes, maybe we could think about a more general graph relation.

**Comment by sorenbs** [comment]
Thanks for the proposal. This is not a feature that will be build into the API. Instead  you should model your data structure to support this use case.

Feel free to reopen this issue if you think that is unreasonable :-)
