### ISSUE TITLE
Local mock server for offline development

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#224]
In some cases it might be needed to have a local mock server for offline development with a in-memory datastore. It basically could look like this:

```sh
graphcool mock my-schema.graphcool

> Local GraphQL server running on https://localhost:8080
```

> Thanks a lot to @BrandonBloom for the suggestion

**Comment by lastmjs** [comment]
Definitely would love this. Testing would be much quicker and we would be able to isolate our tests more easily from other team members also running tests against the same DB. Running all of the tests against a local graph.cool instance would fix that problem.

**Comment by sedubois** [comment]
Would be great! Useful when traveling, in continuous integration testing, etc.

**Comment by pie6k** [comment]
Hmm... sound cool, but I would be first who would use it to simply host it on my own. It's like open-sourcing graph.cool engine. Pretty sure they will not do this (at least not as a feature)

**Comment by sorenbs** [comment]
@pie6k pretty sure we will do this :-)

**Comment by schickling** [comment]
Surprise @pie6k! In case you haven't read our [recent announcement](https://blog.graph.cool/introducing-the-graphcool-framework-d9edab2a7816). 🎉

**Comment by schickling** [comment]
I've created a new issue to track the progress on mocking #1187

**Comment by pie6k** [comment]
@schickling yup! that was a huge surprise! Thanks guys and good luck!
