### ISSUE TITLE
Make it easier to run queries or mutations in inline functions

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#234]
Right now, you need to use a HTTP/GraphQL client to communicate with the project's API.

**Comment by perrosnk** [comment]
+1

**Comment by jhalborg** [comment]
Not only would an easier integration be nice, but the way it works currently scales horribly with number of requests. 

Example use case: 

The client sends a mutation to the server with an update to an entity. A function is invoked, and the job of this function is to calculate and provide meta-data/stats based on that entity. This means that the function will have to make a request for some more data, do the calculations and then post the results to the server. This will lead to one mutation resulting in billing of 3 requests to the api: 

1 mutation from the client
1 query from the function
1 mutation from the function

Furthermore, I was planning to spread out the calcualtion jobs into seperate functions, but that would lead to 

1+(2*number-of-functions) 

queries each time. Let's take the Instagram example - the client uploads a post, and two functions are triggered - one to calculate new number of posts for the user, and one to calculate average time between posts. This would lead to 5 requests in billing. 

I'm aware that each request of course has an impact on Graph.cool's bills as well, but I wanted to raise the issue

**Comment by kbrandwijk** [comment]
+1 for a Graphcool SDK!

**Comment by marktani** [comment]
From schema extension functions that get injected a root token, you can do

```
const fromEvent = require('graphcool-lib').fromEvent
const graphcool = fromEvent(event)
const api = graphcool.api('simple/v1')
```

to initialize a new instance of `graphql-request` for your Simple API endpoint. Then you can do 

```
function getGraphcoolUser (githubUser) {
    console.log('Getting Graphcool user...')

    return api.request(`
      query {
        __type(name: "String") {
          name
        }
      }
    `)
    .then(response => {
      console.log(response)
      return {}
    })
}
```

to query your API.

**Comment by marktani** [comment]
https://github.com/graphcool/graphcool-lib is the way to go 🙂
