### ISSUE TITLE
Enhance __schema, __type and _...Meta to return read-only or system flag on system fields

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#235]
Currently, it's not possible to determine based on the schema, type definition or meta information, which fields are read-only or system fields.
This would be really helpful on the client to determine which fields cannot be edited and which fields cannot be part of an update mutation.

**Comment by marktani** [comment]
I agree that there is a benefit in having this information part of the schema - however, you can determine the available input fields of a mutation using the GraphQL schema already so that's another route that you can explore.

**Comment by kbrandwijk** [comment]
@marktani Could you show me how that works, so I can see if that fits the requirement?

**Comment by marktani** [comment]
Here's an [introspection query](https://www.graph.cool/docs/faq/graphql-introspection-queries-shoe5xailo/) that returns all mutations and their input arguments:

```graphql
query mutationInputArguments {
  __type(name: "Mutation") {
    name
    fields {
      name
      args {
        name
      }
    }
  }
}
```

I just added this example to the FAQ article as well 🙌

**Comment by kbrandwijk** [comment]
I have absolutely no way of seeing how that would even remotely translate to being a viable solution.

You are saying that when I run a query (which may contain nested Types), I have to run a separate __type query on Mutation to get a list of Types with their input parameters, for each type in my resultset cross-reference those fields with the input parameters, to see which ones are not in there, and know that way which fields are read-only.

**Comment by kbrandwijk** [comment]
This has become mostly irrelevant with `User` no longer being a system type.
