### ISSUE TITLE
Allow reference to existing node by any unique field in nested mutations

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#257]
Currently, the only way to reference an existing node in a nested mutation is by Id. It would be helpful for a variety of use cases to be able to reference an existing node by another unique field.

For example, referencing an existing user by email address.
But it would also be really helpful during data import (referencing child nodes by the unique 'oldId' field).

**Comment by aurnik** [comment]
This would be very helpful for me as well, there are many instances where we are pulling from external data sources that do not have our GCool IDs but do have other information that we are using in unique fields. This would save us a query on each item trying to get the ID.

**Comment by kbrandwijk** [comment]
For example, this would create a new post, linking it to the `Author` node with unique field name = 'John'
```
createPost(input: { title: "Test", author: { by: { name: "John" } } })
```
It could be nested:
```
createFlightTicket ( destination: { by : { airPortCode: "AMS" } }, passenger: { by: { passport: { by: { number: "123x45z" } } } })
```
In which airPortCode and passportnumber need to be unique fields

**Comment by pcooney10** [comment]
+1

Very useful when syncing data between projects where objects have different id's.

**Comment by nscarlson** [comment]
+1

**Comment by sorenbs** [comment]
This is a great suggestion. Initial spec being fleshed out in https://github.com/graphcool/framework/issues/1267
