### ISSUE TITLE
Add value to Array field in mutation

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#267]
If you have a Type with a `[String!]` field, it might be useful to get a mutation syntax that supports adding to the existing Array.

**Comment by sorenbs** [comment]
Please see this proposal for our suggested implementation: https://github.com/graphcool/framework/issues/1275

This feature requires a fundamental change to the data structure for scalar lists, so it would be very valuable to get feedback on the suggested functionality as soon as possible, so we can make sure the new data structure supports all required features.

**Comment by gustawdaniel** [comment]
Is this solved?

link https://github.com/graphcool/framework/issues/1275 gives 404

**Comment by onyegood** [comment]
@gustawdaniel please help, I still face this problem, can I see your data model? and what your id look like

//Here is my createRole mutation
async createRole(parent, args, { prisma, request }, info) {
        getUserId(request);

        const { permissions, name } = args.data;

        return prisma.mutation.createRole({
            data: {
                name,
                permissions: {
                    connect: [{ id: permissions }]
                }
            }
        });
    }

//Here is my createRoleInput
input CreateRoleInput {
  name: String!
  permissions: [ID!]!
}

//Here is what I'm sending from GraphQL Playground
mutation {
  createRole(data:{
    name: "Super Admin"
    permissions: ["cjyviw68f160l0785xgy61evq", "cjywrqnab1hwt0785t6ztxj02"]
  })
  {
    id
  }
}

**Comment by gustawdaniel** [comment]
@onyegood It is because of you have array of ID in your model of input but you assigning this array to single `id` in mutation.

Of course in your QraphQL Playground example everything should work.

In backend code you can try

```
async createRole(parent, args, { prisma, request }, info) {
   getUserId(request);
   const { permissions, name } = args.data;
   return prisma.mutation.createRole({
      data: {
         name,
         permissions
      }
   });
}
```

or

```
async createRole(parent, args, { prisma, request }, info) {
   getUserId(request);
   const { permissions, name } = args.data;
   return prisma.mutation.createRole({
      data: {
         name,
         permissions: {connect: permissions.map( p => ( {id: p} ) ) }
      }
   });
}
```

I assuming that you have 

```
permissions =  ["cjyviw68f160l0785xgy61evq", "cjywrqnab1hwt0785t6ztxj02"]
```

For next comments please use syntax with 

```
\ ```
```

to mark code.

https://en.support.wordpress.com/markdown-quick-reference/

**Comment by onyegood** [comment]
@gustawdaniel Much thanks, option 2 solved my problem. I am very grateful
