### ISSUE TITLE
Introduce 'customer alias' in API endpoints

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#269]
Project aliases now have to be globally unique across all your customers. Maybe over time, you can include a 'customer alias' in the endpoint url, like https://api.graph.cool/v1/customer-alias/project-alias.

**Comment by sorenbs** [comment]
Related to https://github.com/graphcool/feature-requests/issues/325

**Comment by sorenbs** [comment]
We will most likely introduce a separate `endpoint` concept that make it possible to create endpoints with a dedicated url that can be pointed at a specific service.

We want to decouple service ids from the endpoint where they can be accessed.

**Comment by marktani** [comment]
Please continue the discussion here: https://github.com/graphcool/framework/issues/1329 🙂
