### ISSUE TITLE
Add option to disable root level query generation on Types

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#285]
For some Types, it does not make sense to query them directly. For example, Orderlines on Orders, Address on Contact, etc. It would be nice to have an option on the Type definition in the Console to disable 'direct' access. This would also make permission queries a lot easier, because if a Type cannot be queried directly, there's also no need to protect it using permission queries.

**Comment by marktani** [comment]
I migrated this to [a feature request](https://github.com/graphcool/feature-requests/issues/286).

**Comment by kbrandwijk** [comment]
Use case: If I have an object hierarchy, 3 layers deep (let's say a House, has Rooms, has Cupboards, has Items) and I want to set permissions on reading all of those rooms, cupboards and items based on being the owner of the House (House has User field), then I have to write permission queries with increased complexity for House, Room, Cupboard and Item.

Without top-level access to Room, Cupboard and Item, I only have to set permissions on House, because the rest of the object hierarchy can only be accessed through House.

**Comment by kbrandwijk** [comment]
Superseded by the Gateway pattern.
