### ISSUE TITLE
Directive Naming

### ISSUE THREAD

**Issue by pksunkara** [graphcool/framework#321]
I was trying out GraphCool's IDL and I realised that the directives you guys are using are unnecessarily long. 

For unique constraint, you guys are using `isUnique` instead of simply `unique` 

For default, you guys are using `defaultValue` where simply using `default` is enough. 

I have worked on schema definition syntax for [API Blueprint](https://apiblueprint.org) and there are many pitfalls people can fall into. This one is just one of many. 

So, I would propose to rename those directives and revisit any other directives I might have not seen. I will be happy to help in standardizing some of these directives (including validation related ones) because it will be a benefit to the whole GraphQL community.

Thanks.

**Comment by kbrandwijk** [comment]
The GraphQL spec currently recognizes 3 directives: `@skip`, `@include`, `@deprecated`. It also describes directives in general. That's about the level of standardization you get from the spec. Anything beyond that is an implementation detail.

Apart from that, I don't agree with you on the naming proposal either. `defaultValue` specifies the default value for a field. For a directive named `default`, I wouldn't expect any argument, and I would interpret it as that field being the default field (for what?). 

As for 'standardization' and `unique`, R uses `is.Unique`, .NET uses `IsUnique` (MVC, Linq, EF, ...), Apple Core Spotlight uses `isUnique`, UML uses `isUnique`. I'm sure you can find an equal amount of platforms that use `unique`...

But that's just my personal view on this.

**Comment by pksunkara** [comment]
When I mean standardizing the spec, I mean in graphcool. Not in the main GraphQL spec.

Currently, we are using `@defaultValue(value: false)`. See the word `value` appearing twice?

Schema of an SQL table uses `UNIQUE` and `DEFAULT`. I think we should have as much of an similarity between that and the directive names.

**Comment by kbrandwijk** [comment]
Why? GraphQL has nothing to do with SQL tables, and neither does Graphcool. By the way, SQL uses `UNIQUE` for the constraint, and `isUnique` on the corresponding index.

Also, the word 'value' appears twice because the directive indicates a 'default value', and the parameters indicates what that 'value' is.

You can have your personal opinion about naming things, butit  has nothing to do with standardizing.

**Comment by marktani** [comment]
Thanks for the discussion @pksunkara @kbrandwijk!
In 1.0, we are rehauling directive names to be more concise (`@default` and `@unique`).

Please continue the discussion here: https://github.com/graphcool/framework/issues/1380
