### ISSUE TITLE
Add directive to auto-fill User relation fields

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#334]
Fill any User relation field that has a certain directive (@currentUser?) with the current user from the request context.

Now, you have to pass the userId as mutation parameter, even when executing the mutation as authenticated User, because you don't have access to that User anywhere.

**Comment by sorenbs** [comment]
I think this touches a broader concept of server-generated variables.

https://github.com/graphcool/feature-requests/issues/332 is the same kind of idea

**Comment by sorenbs** [comment]
See also https://github.com/graphcool/graphcool/issues/355

**Comment by kbrandwijk** [comment]
This is something that clearly belongs in the Gateway.
