### ISSUE TITLE
Add mock data based on schema

### ISSUE THREAD

**Issue by cezarneaga** [graphcool/framework#343]
Introduce functionality similar to [faker](https://www.npmjs.com/package/Faker) into the console. 
Click `mock data` => choose the `type` for which you want data => choose `number` of entries => bamm :)

i am aware this sounds easier than done. :) not sure how it could follow relationships between types, etc. but hey, just throwing it in there.

**Comment by FredyC** [comment]
I agree. This is something I am kinda missing compared to Apollo server implementation which allows to define mocks very easily so frontend developer can work without distraction and waiting for backend to prepare real faked data.

In Apollo it's possible to simply do this...
```
  const mocks = {
    ID: () => {
      idCounter += 1
      return idCounter
    },
    String: () => 'It works!',
    DateTime: () => new Date(casual.unix_time * 1000),
    Game: () => ({ title: casual.title, description: casual.description }),
    User: () => ({ name: casual.full_name, email: casual.email }),
  }
```

Regarding relations, it would probably have to work similarly to nested mutations so you can just specify data for a nested type and it will be created for you.

**Comment by sorenbs** [comment]
Could this be a directive on the model definition?

```graphql
type User {
  id: ID @isUnique
  name: String @mock(generate: "english-name")
  age: String @mock(max: 99, min: 35)
}
```

**Comment by kbrandwijk** [comment]
As I have said in another issue, don't misuse the schema definition to store this kind of information. This could be part of the project file, or part of a seperate test definition file, but does not belong in the schema.

**Comment by FredyC** [comment]
We should probably elaborate more on use cases to figure out the best approach here.

One case use is to be able quick start a project development, see some data while writing queries/mutations. The big pain point here is generated ID. When they are different for an each request, there is no continuation and it does not reflect properly on how would real data behave. For other types, it's not that critical being able to define specific rules for mocked data and it could be simply something default for each type, eg. strings could be composed of random number and name of the field.

Second use case is some sort of test phase when you want to quickly iterate over a bunch of autogenerated data based on some rules and see if your app behaves correctly for different inputs, eg. sometimes sending `null` based on type definition. Might be also useful for automated integration testing, but these need to be more deterministic. To have a fixed set of data that can be mutated and then reset to initial state again.

Is there another use case I am missing?

I agree that using directives for this is a bit overboard. It wouldn't even work for automated testing. Perhaps there could be some sort of sandbox database + endpoint that can be bootstrapped by either clone of data from a real database or based on some rules defined in a config. It could be controlled from CLI to add/remove/reset these sandbox database. Import of data from JSON over CLI would be useful too.

Let's brainstorm more :)

**Comment by marktani** [comment]
I think this should rather be solved with a small lib _outside_ the framework, that just generates a mock JSON based on the schema file. It should be imported as actual data to the project.

**Comment by kbrandwijk** [comment]
So I would say: schema + mock config = mock data (outside the framework), with an easy way to include it in your `gc deploy` (as part of the framework), especially when using local.

For that 'outside the framework' part, 'someone' could take inspiration from how Apollo Server deals with mock data (as mentioned by @FredyC [here](https://github.com/graphcool/graphcool/issues/343#issuecomment-323573674)).

**Comment by schickling** [comment]
I've created a new issue to track the progress on mocking #1187
