### ISSUE TITLE
Current user mutation

### ISSUE THREAD

**Issue by FredyC** [graphcool/framework#347]
It's very handy that we can do query returning currently authenticated user.
```
query {
  user { id }
}
```
It would also great if we could run mutation against such user instead of regular `updateUser` which needs `id` specified.
```
mutation ($name: String) {
  user(name: $name) { id }
}
```

**Comment by marktani** [comment]
That's a great use case for a [custom mutation using Schema Extensions](https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405?u=nilan).

**Comment by FredyC** [comment]
@marktani I thought about that, but wouldn't it be more performant if processed natively? I mean do you need to run query against for current user also? If answer is yes then custom mutation is viable way to go.

Perhaps it might worth to actually have this custom mutation already in place for new accounts. It would serve as an simple example and useful feature too.

**Comment by FredyC** [comment]
Ok so I tried to do this with custom mutation, but there are certain obstacles I cannot cross. For starters, this mutation cannot be made universal meaning that whenever user type is updated, the mutation needs to reflect the change.

Also, the schema extension SDL requires declaring the return type. It's not possible to use User type directly.

So with these findings, I think it would be worth it to be included in Graphcool itself.

**Comment by marktani** [comment]
> Also, the schema extension SDL requires declaring the return type. It's not possible to use User type directly.

This is an improvement covered in #318.
But including such a mutation directly could still be interesting, thanks!

**Comment by FredyC** [comment]
Obsolete for 1.0 :)
