### ISSUE TITLE
Add server-to-server authentication method using 'client_id' and 'client_secret'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#362]
In order to talk to the Graphcool endpoints, you always need a PAT. Almost every other system out there that uses server-to-server communication uses the client_id/client_secret pattern. It would be helpful to be able to authenticate to Graphcool using these values instead of a PAT.

Background for this: the PAT is really long, and not all systems allow you to easily store it (for example, it doesn't fit in the metadata field at Auth0.

I would like to get a mutation for this in the System API, exposed through `graphcool-lib`.

**Comment by sorenbs** [comment]
Do you need to be able to set your own secret, or simply to specify the length of a rootToken (formerly PAT) ?

**Comment by kbrandwijk** [comment]
Well, I don't mind it being generated. The main issues are that the PAT is too long (1) and also not opaque (2).

**Comment by kbrandwijk** [comment]
Closed as part of the Graphcool 1.0 spec.
