### ISSUE TITLE
Error when projectId is empty is not returned to the user.

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#389]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Thursday Jun 22, 2017 at 15:53 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/137_

----

**Comment by marktani** [comment]
This is fixed.
