### ISSUE TITLE
Authenticated permissions don't work with subscriptions when a different type than User is used

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#406]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday Jul 11, 2017 at 12:08 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/177_

----

**What is the current behavior?**

A permission error is returned when you query data with a subscription that is only accessible to authenticated users but your auth token is not corresponding to the `User` type, but for example to the `Customer` type.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type Customer {
  id: ID!
  secret: String!
  isVerified: Boolean!
}

type Message {
  id: ID!
  text: String!
}
```

only allow `AUTHENTICATED` users to access a message's `title`, (`Customer` is used with the anonymous auth provider)

**If applicable, share the query, mutation or subscription for reproduction**

Have a subscription with the `Authorization` token from an existing customer:

```graphql
subscription {
  Message(filter: {
    mutation_in: [CREATED]
  }) {
    node {
      title
    }
  }
}
```

Create a new message:

```graphql
mutation {
  createMessage(title: "Hi") {
    id
  }
}
```

You'll receive an insufficient permission error.

**What is the expected behavior?**

You should receive the data instead of an error.

**Comment by steve-a-jones** [comment]
@marktani - Is my issue here (at the bottom) related? I've been struggling with getting authenticated subscriptions working at all. Currently it only works when I set permissions to "*". No auth token types are working for me (root, User, etc..).

https://www.graph.cool/forum/t/authentication-token-for-subscriptions/839/6

**Comment by marktani** [comment]
This was an issue in the example code this occured with, not in the backend. Closing this 🙂
