### ISSUE TITLE
update/delete by 

### ISSUE THREAD

**Issue by KApo09** [graphcool/framework#45]
Use case: 
My user model has two unique keys. a) GraphQLID b) FacebookId. Would be great  to update the User Model directly via the FacebookId without the need to first query the GraphQLID.
Example:
```
 updateUser(idFb:"12233232", state: MAIN)
{
    state
  }
```

**Comment by timsuchanek** [comment]
In the near future we want to add filters to the update mutations, that should cover your use case :)

**Comment by marktani** [comment]
Same for delete by

**Comment by Kaihuang724** [comment]
Use case:

My user node has a relationship with another data node. I want to update the User node's relationship using a (unique) variable other than the ID.

Example where goals is the relationship:

```
  mutation updateUser($id: ID!, $name: String, $age: Int, $gender: USER_GENDER, $goalsNames: [String!]) {
    updateUser(
      id: $id,
      name: $name,
      age: $age,
      gender: $gender,
      goalsNames: $goalsNames
    ) {
      name,
      goals {
        id,
        name
      }
    }
```

**Comment by marktani** [comment]
Closing in favor of https://github.com/graphcool/framework/issues/1267.
