### ISSUE TITLE
Don't put .graphql files in code folder

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/framework#537]
Copied over from https://github.com/graphcool/graphcool-cli/issues/186 as this is backend related

**Comment by sorenbs** [comment]
See https://github.com/graphcool/graphcool/issues/543

I suggest this structure:

### code
all js files and resolver schemas. Resolver schemas will later be moved to types.graphql

### subscriptions
all subscription queries

@timsuchanek @marktani Does this sound good to you?

**Comment by kbrandwijk** [comment]
@sorenbs The example project that `gc init` creates, already puts .graphql files in a different folder for SE's...

**Comment by marktani** [comment]
related to #602
