### ISSUE TITLE
Image API resize rotates some images

### ISSUE THREAD

**Issue by meikoudras** [graphcool/framework#570]
**What is the current behavior?**
When resizing an image with the Image API the image appears to be rotated. The original is unaffected.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

Original image:
https://images.graph.cool/v1/cj6dot2vz3du90121dvxaaqlo/cj7oh8sgy00kc0151f6ibpurc/
Resized image
https://images.graph.cool/v1/cj6dot2vz3du90121dvxaaqlo/cj7oh8sgy00kc0151f6ibpurc/400x
https://images.graph.cool/v1/cj6dot2vz3du90121dvxaaqlo/cj7oh8sgy00kc0151f6ibpurc/x400

**What is the expected behavior?**
That the image rotation stays the same as the original

**Comment by meikoudras** [comment]
Probably related to this:

https://github.com/lovell/sharp/issues/903

**Comment by Olu93** [comment]
Has this been solved already?
My pictures which have higher vertical dimensions than horizontal dimensions are rotated on resize and it seems totally random in which direction and on which image it actually occurs.

This is my transformation code
`function resize(buffer) {
    return Promise.resolve(sharp(buffer))
        .then(imageBuffer => imageBuffer.resize(200, 200))
        .then(resizedImage => resizedImage.png())
        .then(pngImage => pngImage.toBuffer())
        .catch(err => ({ msg: "Error resizing image", err: err }))
}`

**Comment by kbrandwijk** [comment]
@Olu93 If you are resizing images yourself using sharp, that doesn't seem related to the Image API...
