### ISSUE TITLE
Stream function/request logs to Cloudwatch, Loggly...

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#586]
Operating bigger projects requires better tooling around logging. It would be helpful if request & function logs (and others) can be forwarded automatically to a logging service such as Cloudwatch, Loggly etc.

[Docker logging drivers](https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers) might be an interesting source of inspiration.

**Comment by zsherman** [comment]
I've been playing around with graphcool over at [Timber](https://timber.io), we'd love to help out with this if we can.

**Comment by sorenbs** [comment]
See also this proposal: https://github.com/graphcool/graphcool/issues/749

**Comment by kbrandwijk** [comment]
I have been doing this manually in my functions, using a library that overrides my `console.....` statements to go to Loggly, but it would be nice if this could be configurable from the service configuration (graphcool.yml).

**Comment by marktani** [comment]
Discussion will be continued in #749. 🙂
