### ISSUE TITLE
Filters should support scalar lists

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#60]
The following filters should be supported for scalar lists:

```
field_contains: T # contains single scalar T
field_contains_every: [T] # contains all scalar T
field_contains_some: [T] # contains at least 1 scalar T
```

**Comment by marktani** [comment]
What about these?

```
field_not_contains: T # does not contain single scalar T
field_contains_none: [T] # does not contain any scalar T
```

**Comment by sorenbs** [comment]
Good point!

**Comment by gCardinal** [comment]
Adding my voice, this would be really nice to have. More filters is always good!

**Comment by marktani** [comment]
@frederickfogerty does the proposed API cover your use case?

**Comment by frederickfogerty** [comment]
@marktani yep, the simple `field_contains` is enough to cover our use case

**Comment by matthiasak** [comment]
+1 for this

**Comment by utunga** [comment]
yes please!

**Comment by dohomi** [comment]
this is important for me too:
```
field_contains: '%somestring%' => similar to LIKE %string% from MySQL filter
```

**Comment by philcockfield** [comment]
Any movement on this guys?  Is filtering within an array of values likely to drop anytime soon?  Would be particularly helpful to my use-case.

Thanks.

**Comment by petteriinnanmaa** [comment]
+1

**Comment by emilbruckner** [comment]
+1

**Comment by superfunkminister** [comment]
+1

**Comment by aurnik** [comment]
This is necessary for me right now. The only extra thing I would say is to support unique scalar lists for directly querying a node. For example, if I have a schema like
`
Agent {
  aliases: [String!] @isUnique
}
`
It would be nice to be able to query directly by any of the aliases in the list.

**Comment by marktani** [comment]
This feature request will not be covered in the near future. There is a straight-forward work around as follow:

If you want to filter a list of strings `tags: [String!]!`:

```graphql
type Item @model {
  id: ID! @isUnique
  tags: [String!]!
}
```

you can introduce a new type `Tag` with a single `key: String` field and connect `Item` to `Tag` one-to-many or many-to-many:

```graphql
type Item @model {
  id: ID! @isUnique
  tags: [Tag!]! @relation(name: "ItemTags")
}

type Tag {
  id: ID! @model @isUnique
  key: String!
  item: Item @relation(name: "ItemTags")
}
```

Now you can filter items based on their connected tags using the `tags_none`, `tags_some` and `tags_every` filters:

```graphql
# query all general items
query {
  allItems(filter: {
    tags_some: {
      key: "general"
    }
  }) {
    id
  }
}
```

---

Please use Github reactions instead of short comments.

**Comment by frederickfogerty** [comment]
If someone has scala knowledge and some free time, I believe it requires writing some SQL and updating the files:

https://github.com/graphcool/framework/blob/9d9dd4c76a9519ee72a8a2e5b7be829ec3c24cd3/server/backend-shared/src/main/scala/cool/graph/client/database/QueryArguments.scala
and
https://github.com/graphcool/framework/blob/9d9dd4c76a9519ee72a8a2e5b7be829ec3c24cd3/server/backend-shared/src/main/scala/cool/graph/client/database/FilterArguments.scala

**Comment by sorenbs** [comment]
Thanks for the input everybody!

Please see this proposal for our suggested implementation: https://github.com/graphcool/framework/issues/1275

This feature requires a fundamental change to the data structure for scalar lists, so it would be very valuable to get feedback on the suggested functionality as soon as possible, so we can make sure the new data structure supports all required features.

**Comment by niekert** [comment]
Fixed link to the issue for future visitors: https://github.com/prisma/prisma/issues/1275
