### ISSUE TITLE
Tweak pluralization rules

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#604]
Type names ending in -o, get a plural form ending in -oes.
The standard spelling rule is -o -> -os. The -oes is rather an exception than a rule.

Can you change the standard pluralization rule for Types to use -os instead of -oes?

**Comment by iamclaytonray** [comment]
To go along with @kbrandwijk, here's some screenshots for extra clarity

<img width="746" alt="screen shot 2017-09-27 at 12 53 46 pm" src="https://user-images.githubusercontent.com/16495816/30927361-3c8989fc-a386-11e7-8294-c1c5bd1920a0.png">
<img width="487" alt="screen shot 2017-09-27 at 12 53 33 pm" src="https://user-images.githubusercontent.com/16495816/30927360-3c8900fe-a386-11e7-9506-226313d40458.png">

**Comment by schickling** [comment]
Closed in favour of #1342
