### ISSUE TITLE
Import command

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#610]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Saturday Feb 25, 2017 at 18:45 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/1_

----

## Challenges & Edge cases

- [ ] Performance
  - [ ] The JSON file should be read as a stream to work with big JSON files (>100mb). [JSONStream](https://github.com/dominictarr/JSONStream) seems like a good fit.
  - [ ] Use an async mapper which allows for chunking (X mutations per request) and guarantees that not more than Y HTTP requests are active at the same time
  - [ ] Bonus: Show import progress
- [ ] Schema & data
  - [ ] Enforce values for required fields
  - [ ] Trim values for fields not being part of the schema
- [ ] Defensive error handling

## Tradeoffs

- The first version of the `import` command probably won't be able to handle relations and nested data. That's something that should be discussed in the comments.

## Import format

The JSON dump has to be an object with the root properties matching the GraphQL type names (e.g. `Movie` and `Actor`)

### Schema

```graphql
type Movie {
  oldId: Int! @isUnique
  voteCount: Int!
  voteAverage: Float!
  title: String!
  originalTitle: String!
  originalLanguage: String!
  description: String!
  releaseDate: DateTime!
}

type Actor {
  name: String!
}
```

### Dump

```json
{
  "Movie": [
    {
      "oldId": 297762,
      "voteCount": 997,
      "voteAverage": 7.1,
      "title": "Wonder Woman",
      "originalLanguage": "en",
      "originalTitle": "Wonder Woman",
      "description": "An Amazon princess comes to the world of Man to become the greatest of the female superheroes.",
      "releaseDate": "2017-05-30T00:00:00.000Z"
    }
  ],
  "Actor": []
}
```

### Usage

```sh
$ graphcool init --schema http://graphqlbin.com/movies-import.graphql
$ curl http://static.graph.cool.s3.amazonaws.com/dumps/movies.json > movies.json
$ graphcool import movies.json --batch 20
```

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Jun 14, 2017 at 20:46 GMT_

----

Proposal for the dump: use [ndjson](http://ndjson.org/). It's used specifically for larger imports. Because it contains one json object per line, objects stay considerably smaller than using the array notation above. That will effectively create one huge JSON object for each table. The ndjson variant would look like:

`{ "Movie": {  "oldId": 297762, "voteCount": 997, "voteAverage": 7.1, "title": "Wonder Woman", ... } }`
`{ "Movie": {  "oldId": 12345, "voteCount": 997, "voteAverage": 7.1, "title": "Wonder Woman", ... } }`
`{ "Actor": { .... } }`
`{ "Actor": { .... } }`

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Wednesday Jun 14, 2017 at 20:51 GMT_

----

The problem with that I'm seeing that it's more difficult for developers to prepare their dumps in this format as most use cases would be an initial import and not a export-reimport process.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Jun 14, 2017 at 20:56 GMT_

----

Well, that depends where they get their JSON from... This format is way easier to stream because every record is an object, and it's an open standard.

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Thursday Jun 15, 2017 at 09:39 GMT_

----

Analysing the complexity of this a bit further we probably want some sort of **import mode** possibly enabling the following points:

* Don't count requests towards the monthly request quota (Might require disabling of conventional reads/writes to the project during this time)
* Provide existing `id` fields (would require checks on some global properties (uniqueness, ordering...))
* Temporarily lift required relations constraint to import data in two steps (1. import nodes 2. import edges)

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Thursday Jun 29, 2017 at 20:10 GMT_

----

The usage should roughly work like this `graphcool import my-dump.sql` or `graphcool import data.csv` which would do the following: 

1) The CLI would make use of a new package called `graphcool-normalize` that can transform any kind of input data (json, sql, csv…) to a normalized format (which is specified by us). All of these transformations can be unit tested and don’t have to care about HTTP server responses at all. This allows us to test very sophisticated edge-cases with very little effort. Another nice benefit of this, is that other community members can implement their own transformations.

2) The normalized data (which we should probably temporarily safe into a local file) will then get uploaded to the Graphcool api. This should be fairly simple and I think the following two step process makes sense:

2.1) Upload all normalized nodes to Graphcool. 
2.2) After all nodes have been uploaded, the related nodes can be “connected” via the corresponding mutations

A few further notes:
* Almost every step can be batched + streamed
* We should make the entire process error-resilient + repeatable. That means if the command fails at some point, it should be possible to resume without ending up in an inconsistent state
* We probably need to temporarily “soften up” the schema to enable step 2 in the case of required relations. That means before the import all required relations need to become optional and reset again after 2.2
* To properly implement step 1 + 2 we need the type information based on the GraphQL schema
* I think it's a fair assumption to say that the import command is just used for initial import and not for continuous syncing

**Comment by sorenbs** [comment]
Please see https://github.com/graphcool/framework/issues/1299

**Comment by marktani** [comment]
This has now been released in the [latest version of `graphcool-framework`](https://github.com/graphcool/framework/releases/tag/0.11.4) and the [latest developer preview of Graphcool 1.0](https://github.com/graphcool/framework/pull/1318#issuecomment-353673128) 🎉
