### ISSUE TITLE
Temp folder not removed after adding template

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#635]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 20:05 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/199_

----

The folder that is used is moved out, but the rest of the repo is left behind in the temp folder.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:18 GMT_

----

Thanks for bringing that up! We should delete the temp folder,

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.

**Comment by kbrandwijk** [comment]
Reopening as this also applies to `add-template`
