### ISSUE TITLE
[1.3.13] Init blank project puts SE SDL in schema folder, pull puts it in code folder

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#643]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 21:34 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/210_

----

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:32 GMT_

----

That's due to the backend needing to adopt the schema folder. Onhold until then.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 10:52 GMT_

----

Is there a related backend issue that could be linked here?

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 11:35 GMT_

----

Not yet, we're discussing it currently how it should be structured. As soon as we have that, I'll update this

**Comment by schickling** [comment]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sorenbs](https://github.com/sorenbs)**
_Tuesday Sep 12, 2017 at 12:18 GMT_

----

Keep in mind that this is a short term concern. Eventually we want to support general types in the `types.graphql` file as described in https://github.com/graphcool/graphcool/issues/543

**Comment by marktani** [comment]
Fixed 😄
