### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#675]
<a href="https://github.com/spoorendonk"><img src="https://avatars0.githubusercontent.com/u/13233275?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [spoorendonk](https://github.com/spoorendonk)**
_Tuesday Sep 26, 2017 at 14:05 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/269_

----

When exporting on Windows 10 I get the following

```
PS C:\code\gc> graphcool export prod.graphcool DEBUG=graphcool
×  Error: invalid json response body at https://api.graph.cool/system reason: Unexpected token < in JSON at position 0

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/

PS C:\code\gc> graphcool version
1.3.7
```

**Comment by schickling** [comment]
<a href="https://github.com/spoorendonk"><img src="https://avatars0.githubusercontent.com/u/13233275?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spoorendonk](https://github.com/spoorendonk)**
_Tuesday Sep 26, 2017 at 19:33 GMT_

----

after upgrading to the beta version
```
PS C:\code\gc2> graphcool version
graphcool/1.3.16-beta.22 (windows-x64) node-v8.5.0
```
I get
```
PS C:\code\gc2> graphcool export
Exporting project... !
 !    GraphQL Error (Code: 502): {"response":{"error":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502
 !    Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n","status":502},"request":{"query":"\n      mutation ($projectId: String!){\n
 !    exportData(input:{\n          projectId: $projectId,\n          clientMutationId: \"asd\"\n        }) {\n          url\n        }\n      }\n
 !    ","variables":{"projectId":"prod"}}}
```

**Comment by marktani** [comment]
Closing in favor of #1299.
