### ISSUE TITLE
Add settings that allows overwriting createdAt/updatedAt

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#69]

**Comment by marktani** [comment]
A similar situation: being able to update a node without actually updating any values:

```graphql
mutation {
  updateNode(id: "some-id") {
     # updatedAt has been updated
     updatedAt
  }
}
```

**Comment by bkcan** [comment]
What's the status on this? We would really like to override these fields because we have to sync Graphcool database with another one. Having createdAt and updatedAt changed only when mutating to Graphcool changes the values and rearranges the order of objects.

**Comment by marktani** [comment]
Closing in favor of https://github.com/graphcool/framework/issues/365
