### ISSUE TITLE
Create mutation response is returning null on deep relation

### ISSUE THREAD

**Issue by robohub** [graphcool/framework#694]
**What is the current behavior?**
The response after a create mutation is returning null on deep relation.

I'am running this mutation, with the response to the right.
Two oppositeRelations are returned; one is "null" while the other is correct (an object with id="cj81k0w44htur0151dgayfxq9").
![image](https://user-images.githubusercontent.com/3430753/31017766-f5faf188-a529-11e7-9ead-fc4e6fcc15b4.png)

**What is the expected behavior?**
The null value should be an object with id="cj81jy0whhsi50151655why1i" according to this data:
![image](https://user-images.githubusercontent.com/3430753/31017845-366574c8-a52a-11e7-979b-3184b5455fda.png)

Is this a bug, or am I doing things wrong?

**Comment by marktani** [comment]
Hey @robohub, thanks a lot for your question! Could you provide the relevant part of your types and the needed mutations to reproduce this? 🙂

**Comment by robohub** [comment]
Hi @marktani ! Would it be sufficient to mail you the end-point and a text file with the relevant mutation and queries?

**Comment by marktani** [comment]
Of course 🙂

**Comment by robohub** [comment]
Hi Nilan,

as per request find attached files!

My end-point is:

https://api.graph.cool/simple/v1/cj5s0jl17534v016007jclvnw

Let me know if you need more,

BR Robert

________________________________
Från: Nilan Marktanner <notifications@github.com>
Skickat: den 29 september 2017 15:53
Till: graphcool/graphcool
Kopia: robohub; Mention
Ämne: Re: [graphcool/graphcool] Create mutation response is returning null on deep relation (#694)


Of course 🙂

**Comment by marktani** [comment]
Dear Robert, you replied to the Github thread, so the files were not forwarded 😄 
Please use support@graph.cool instead 🙂

**Comment by marktani** [comment]
Closing this :) @robohub please open another issue if you're still encountering an issue here.
