### ISSUE TITLE
Graphcool init for @beta creates a new project when existing project is selected.

### ISSUE THREAD

**Issue by steve-a-jones** [graphcool/framework#701]
**What is the current behavior?**

`graphcool init` prompts for new or existing project ->
`I` select existing project for project list ->
`graphcool` outputs my selected (existing) project's `name(id)` ->
`graphcool` subsequently outputs `"Creating project <random name>"` ->
`graphcool` proceeds to create a new project (I verified in graph.cool gui) ->
`graphcool` generates starter files (.graphcoolrc, graphcool.yml, types.graphql) for newly created project

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

`yarn global add graphcool@beta`

```
graphcool version
graphcool/1.3.16-beta.26 (darwin-x64) node-v8.6.0
```

The existing project that I selected was newly set up and had not been modified yet with any schema updates or mutations. 

To reproduce go to GUI and create new project, `cd` to a clean dir and run `graphcool init`.

**If applicable, share the query, mutation or subscription for reproduction**

**What is the expected behavior?**

`graphcool` should output project files for an existing project and not create a new one.

**Comment by marktani** [comment]
Hey @steve-a-jones, could you resolve this issue? 🙂 Maybe a better documentation is needed here?

**Comment by steve-a-jones** [comment]
Hey @marktani , initially I was under the impression that `init` for an existing project meant that I would be (re)generating an **existing** configuration into a local project -- somewhat analogous to a `git clone`. 

Later I realized that `init` for an existing project means to "init" a **new** project while generating/copying the config based on an existing project.

`pull` is command you are looking for if this is what you want :)

**Comment by GxDesign** [comment]
graphcool pull -project <project-id> doesnt work currently. Is there a different command to use to pull an existing project?

**Comment by steve-a-jones** [comment]
@GxDesign can you provide steps to reproduce?

**Comment by kbrandwijk** [comment]
`graphcool pull` is deprecated in the Framework Preview. You can upgrade a project from the console, and download the project definition there. @GxDesign does your question apply to the Framework Preview?

**Comment by GxDesign** [comment]
Hey, thanks! I figured that out tonight. I just downloaded the project from the browser. Im not quite sure if my case was regarding Framework Preview but it does seem that its deprecated.

**Comment by marktani** [comment]
Closing this, as the behaviour of `init` was changed in 0.6: https://github.com/graphcool/framework/issues/706
