### ISSUE TITLE
Ability to deploy same function with different environment variables

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#715]
**What feature are you missing?**

Specifying the same environment variable with two different values for two separate functions doesn't work. See here more a more detailed description: https://github.com/graphcool/modules/issues/21.

The reason this is currently the case, is that the function is actually only deployed once. We should think about a better workflow for deploying a similar functions with different env variables.

**Comment by kbrandwijk** [comment]
Is that actually the reason. I didn't test this, but if you specify two different code files, but still reuse environment variable names, would *that* work as expected?

**Comment by marktani** [comment]
good point, I haven't tried it 🙂 it probably makes sense to tackle all of that together

**Comment by marktani** [comment]
Closing in favor of #1203.
