### ISSUE TITLE
Graphcool pull case sensitivity

### ISSUE THREAD

**Issue by eruby94** [graphcool/framework#716]
@marktani Please enable graphcool-cli to ignore case sensitivity when pulling a project.

Currently, only a lowercase y, and an uppercase N are accepted. It would make sense to accept either for developer's preference.

If it is decided that you wish to retain the case sensitivity, some user-friendly logging should be added to request a proper response. For example, pressing Y just kills the script, no output is made, and one could be confused if it was accepted (it was not). Should be fairly simple to modify the prompt commands.

**Comment by marktani** [comment]
Hey @eruby94, could you help me understand which prompts you are talking about? 🙂

**Comment by eruby94** [comment]
![screen shot 2017-10-03 at 12 04 57 pm](https://user-images.githubusercontent.com/12565404/31135503-2cf22c86-a833-11e7-8fe6-8ec6f1524522.png)

If I entered 'Y' as opposed to 'y', the script does not accept the input and aborts with no output

**Comment by kbrandwijk** [comment]
All confirmation prompts are case-insensitive in the latest CLI version.
