### ISSUE TITLE
Scalar Payloads for Resolver Functions

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#729]
**What feature are you missing?**

Returning a scalar value for a resolver function is not supported currently.

**How could this feature look like in detail? Tradeoffs?**

```graphql
extend type Query {
  add(a: Int! b: Int!): Int!
}
```

```js
module.exports = function sum(event) {
  const data = event.data

  const sum = data.a + data.b

  return {data: sum}
}
```

Currently, if you store such a resolver function, you receive this error message:

> Schema Extension Error for function 'A': Must provide return type. For example: type MyPayload { someField: Boolean }

**Comment by FredyC** [comment]
I think this is kinda related to generally being able to return any existing type from your schema. Unless that's already working and I've missed it :)

**Comment by kbrandwijk** [comment]
No, it's not. The primitive types are not linked to storage, and using them in resolver functions is something that's a lot different from integrating Resolver Function payload Types with the storage Types.

**Comment by schickling** [comment]
Looks like a great and natural addition to resolver functions!

**Comment by marktani** [comment]
Further discuss in #743.
