### ISSUE TITLE
The edit schema button still visible

### ISSUE THREAD

**Issue by FredyC** [graphcool/framework#739]
**What is the current behavior?**

In data explorer for the ejected project, there is an `Edit Schema` button which mostly does nothing.

**What is the expected behavior?**

A button should not be present for the ejected app since schema cannot be edited. On the other hand, it might be nice to keep schema editor in read-only mode just for a quick overview of types and relations.

**Comment by divyenduz** [comment]
+1 for keeping the schema (read-only) and/or maybe the Graph View option for a quick overview.

**Comment by marktani** [comment]
This has been implemented 🙂
