### ISSUE TITLE
Print USAGE.md content when adding a template

### ISSUE THREAD

**Issue by notrab** [graphcool/framework#754]
**What feature are you missing?**

The ability to write and display a custom README for templates that are added via the CLI.

**How could this feature look like in detail? Tradeoffs?**

Instead of printing `README` when a module is added, it could be good to print a custom README that is dedicated for installation tips/next steps.

Currently it displays the README, which often includes parts for adding the module, which looks a bit weird.

Not sure on the best practice for file names, perhaps a dotfiles or a `README.graphcool`.

Love to hear any further thoughts. Apologies if this is a duplicate issue, but I couldn't find one similar before I posted!

**Comment by kbrandwijk** [comment]
I see two options:
- Stick to a convention, e.g. add a `USAGE.md` or similar to the root of the module folder
- Specify which file to display by adding a key to package.json, defaulting to README.md if not specified

**Comment by notrab** [comment]
`USAGE.md` gets my vote @kbrandwijk 😇

**Comment by timsuchanek** [comment]
Including the `USAGE.md` is now implemented
