### ISSUE TITLE
Support multiple type definition files

### ISSUE THREAD

**Issue by jferrettiboke** [graphcool/framework#774]
**What is the current behavior?**

If I split my "types" and "enums" into two different files and add them to the `graphcool.yml` file and then I run `graphcool deploy`, I get an error saying `!    Path must be a string. Received [ './enums.graphql', './types.graphql' ]`.

I am using Windows 10, Node.js v8.6.0 and `graphcool@next` exactly `0.7.0-beta.5` at this moment.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

```yml
types:
  - ./types.graphql
  - ./enums.graphql

# More stuff...
```

**What is the expected behavior?**

It must deploy properly to the platform.

**Comment by marktani** [comment]
`types` is currently a field that accepts a string, not a list of strings. I don't see a problem with supporting multiple type definitions however, great feature request @jferrettiboke!

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/graphcool/pull/783/commits/cac28c0e93dad78ef00116e9ca6380c2a2a7dc95#diff-31d33b0cd5c67b89253567e956f53621R120???

**Comment by marktani** [comment]
Good point! Might be a mismatch in the used json schema then. @timsuchanek?

**Comment by jferrettiboke** [comment]
@marktani It is also on [docs](https://docs-next.graph.cool/reference/service-definition/graphcool.yml-foatho8aip#yaml-structure).

> Examples
>
> Referring to a single type definition file
>

```yml
types: ./types.graphql
```

> Referring to multiple type definition files

```yml
types:
  - ./types.graphql
  - ./customResolver.graphql
```

**Comment by grahamb** [comment]
I understand this is coming in 1.0 (per #1328), but it's still documented as being possible right now. 
![screenshot 2017-11-30 17 36 16](https://user-images.githubusercontent.com/146111/33463942-faab929a-d5f4-11e7-84d4-e385e9205018.png)

Perhaps the documentation should be changed to reflect the current reality?

**Comment by marktani** [comment]
This feature has been added in version `0.10.1`. Thanks for your feedback! 🙌 

https://github.com/graphcool/framework/releases/tag/0.10.1
