### ISSUE TITLE
Custom GraphQL types to be used for functions

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#79]
Ability to define custom GraphQL types, like so

```
type AlgorithmResult {
  users: UserConnection
  meta: Metadata
  tag: String!
}
```

`UserConnection` is already present in the schemas, but `Metadata` is another custom GraphQL type.

This can be used to validate the input/output of functions.

Thanks to @migueloller for the suggestion :+1:

**Comment by kbrandwijk** [comment]
Would that also include custom types for Fields (so Types without a table), or is that a seperate FR?

**Comment by marktani** [comment]
Closing in favor of #743.
