### ISSUE TITLE
Settings/Authentication tab in Console points to the older CLI repository

### ISSUE THREAD

**Issue by divyenduz** [graphcool/framework#807]
**What is the current behavior?**

The URL `https://console.graph.cool/<Project>/settings/authentication`
<img width="607" alt="screen shot 2017-10-14 at 11 51 38 am" src="https://user-images.githubusercontent.com/746482/31573275-1e34d10c-b0d6-11e7-8560-7e480b73181e.png">

Points to the older CLI repo. 

**What is the expected behavior?**

It should point to the newer repository and provide instructions on how the token can be generated. 

Thanks and kudos for the awesome work :)

**Comment by divyenduz** [comment]
Note that this was for a [new format project](https://blog.graph.cool/graphcool-framework-preview-ff42081b1333) (CLI controllable only)

**Comment by divyenduz** [comment]
I think this is resolved now and can be closed. Thanks.

**Comment by marktani** [comment]
Thanks 🙌
