### ISSUE TITLE
add-template command unknown

### ISSUE THREAD

**Issue by tobias7an** [graphcool/framework#812]
When attempting to add a template according to instructions [here](https://docs-next.graph.cool/reference/service-definition/templates-zeiv8phail/), the command 

`graphcool add-template graphcool/templates/authentication/email-password`
fails with
`Unknown command: unknown
`

**Comment by kbrandwijk** [comment]
The template location has changed to: `graphcool/templates/auth/email-password`.
With version 0.7.0 of the CLI, adding the template works.

**Comment by marktani** [comment]
@tobias7an, what's `graphcool version` for you?

**Comment by traversng** [comment]
Getting the same with version 1.3.7
