### ISSUE TITLE
Type error when deploying a cloned project

### ISSUE THREAD

**Issue by do4gr** [graphcool/framework#839]
Cloning this project https://github.com/richardkall/graphcool-hook-issue.git and then doing `graphcool deploy` results in the following error: 
<img width="953" alt="bildschirmfoto 2017-10-16 um 10 54 18" src="https://user-images.githubusercontent.com/16278407/31603875-d55e3364-b261-11e7-8621-5476969f2923.png">

This was without removing the .graphcoolrc file first. After removing it it works.

**Comment by timsuchanek** [comment]
I can't reproduce it. Please reopen if it's still an issue.
