### ISSUE TITLE
Improve "The payloadType for the resolver is not nullable." error message

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#846]
When you have a resolver with required payload type but return `null` from that resolver, you'll receive this error message:

```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "event"
      ],
      "code": 2063,
      "message": "The payloadType for the resolver is not nullable.",
      "requestId": "eu-west-1:simple:cj8ua9zo0000001400sbp7hoe"
    }
  ]
}
```

Instead of 

> The payloadType for the resolver is not nullable.

I'd suggest something like:

> The payloadType for the resolver _resolver-name_ is not nullable, but the resolver returned null.

**Comment by kbrandwijk** [comment]
Another question is: why can a resolver payload be required?

**Comment by marktani** [comment]
```

**Comment by kbrandwijk** [comment]
Because if that mutation returns an error, the result will be:
```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "functionError": "Sum Tin Wong",
      "path": [
        "authenticateUser"
      ],
      "code": 5001,
      "message": "function execution error: Sum Tin Wong",
      "requestId": "eu-west-1:simple:cj...."
    }
  ]
}
``` 
Notice the `data: null` in there, which is a violation of the schema, because the Payload is required, and no null-bubbling can happen.

**Comment by kbrandwijk** [comment]
Never mind, thought train to the wrong destination.
Another question though. If you return null from a resolver with a required payload type, do you really need an error message, or can you just bubble the result and that's it?

**Comment by marktani** [comment]
Good point. I'll think about that! 🙂

**Comment by marktani** [comment]
The error message has been improved, but is still returned in case of a `null` value being returned.
