### ISSUE TITLE
Adding a template does not update types of project file

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#848]
**What is the current behavior?**
If I add a template to my project, my project file and types file are not updated, only the sources are added to src/subfolder.

**What is the expected behavior?**
Get the changes from the template into my types and project file.

0.7.0

**Comment by marktani** [comment]
Could you provide a reproduction? 🙂

**Comment by kbrandwijk** [comment]
`gc init`
`gc add-template graphcool/templates/auth/email-password`

**Comment by kbrandwijk** [comment]
Result:
![image](https://user-images.githubusercontent.com/852069/31621474-140c50c2-b29a-11e7-8cfb-4b2b94a11c28.png)

**Comment by kbrandwijk** [comment]
Unable to reproduce in the current CLI version.
