### ISSUE TITLE
set -x DEBUG "*" does not work on Windows

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#863]
**What is the current behavior?**
Most CLI errors tell you to run `set -x DEBUG "*"`. However, this command does not work on Windows.

**What is the expected behavior?**
Please show platform-specific info where applicable.

**Comment by timsuchanek** [comment]
We're checking if the current `$SHELL` variable ends with `fish`, otherwise we show the `export` command. Which shell are you using on windows?

**Comment by kbrandwijk** [comment]
cmder http://cmder.net/

**Comment by dpetrick** [comment]
The correct command (at least for vanilla `cmd`) is `set DEBUG=*` @timsuchanek

**Comment by kbrandwijk** [comment]
Fixed in the meantime.
