### ISSUE TITLE
local cluster does not exist on windows 7 docker toolbox

### ISSUE THREAD

**Issue by rwatts3** [graphcool/framework#864]
After running `gc local up` , the local cluster is not found when running `gc list` on windows 7.
Therefore when trying to run `gc deploy` , and selecting local results in an error of the local cluster not being found.

**Comment by rwatts3** [comment]
If you can provide instruction on how to retrieve the cluster secret I can try to manually add it to the global `.graphcoolrc` file and see if that helps .

**Comment by timsuchanek** [comment]
Thanks for reporting @rwatts3 ! Can you please post the output of `gc local up` and `docker ps`?

**Comment by marktani** [comment]
Version 0.9 comes with _experimental_ Docker Toolbox support :tada: Please open a new issue if you find any problems on the latest version 🙂
