### ISSUE TITLE
Heroku Integration

### ISSUE THREAD

**Issue by PolywickStudio** [graphcool/framework#866]
**What feature are you missing?**
I need Heroku integration support.

**How could this feature look like in detail? Tradeoffs?**
I asked this in Heroku, they asked me to ask you guys to contact Heroku and add an official repo which someone can use GraphCool in Heroku.

**Comment by marktani** [comment]
We're currently speccing out how an official Heroku integration could look like and will post more information here once that progressed further. Thanks a lot for bringing this up, @PolywickStudio!

**Comment by PolywickStudio** [comment]
I managed to use it in Heroku

**Comment by mzgnr** [comment]
@PolywickStudio can you share how you managed to launch it in heroku or any example project ?

**Comment by joevo2** [comment]
Yeah @PolywickStudio im interested on how it works on heroku as well 😄

**Comment by tannerhallman** [comment]
bump? @PolywickStudio

**Comment by marktani** [comment]
We'll add a heroku integration to Prisma Cloud soon 🙂
