### ISSUE TITLE
Make rate limiting customizable

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#87]
Expose reasonable defaults and offer custom configuration in the console.

**Comment by kabriel** [comment]
yes please! I've already had several cases where a large number of nodes were created (due to a bug) that  rate limit would have helped with. This is also a security concern; if you enable a user to create an node, there is no stopping them from creating millions and wiping out your database.

**Comment by JensMadsen** [comment]
we need this as well. We need methods preventing someone stealing our database (no allType queries )

**Comment by kbrandwijk** [comment]
@JensMadsen Isn't that something that should be prevented with permissions? Rate limiting would just slow it down...

**Comment by JensMadsen** [comment]
I missed a hint somewhere else. Sorry. We need to build gateway

**Comment by marktani** [comment]
Closing in favor of #748.
