### ISSUE TITLE
Show error when old docker-compose is installed

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#904]
When running any `gc local` command, it should first check the docker-compose version and exit with an error when an old version is installed (we need to define which is the minimum version).

The message should show helpful instructions with how to upgrade.

**Comment by kbrandwijk** [comment]
Please show a friendly error message as well if `docker-compose` is not installed. You need to install that separately, and people run into an unfriendly `'ENOENT': spawn docker-compose ENOENT` error.
