### ISSUE TITLE
Improve wording when adding templates

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#936]
<img width="764" alt="bildschirmfoto 2017-10-19 um 18 15 52" src="https://user-images.githubusercontent.com/1780597/31813429-957c8002-b586-11e7-872d-df17eb23122f.png">

* two first lines can be improved
* last line should read 'uncomment' instead of 'comment out'

**Comment by kbrandwijk** [comment]
I think the term is 'uncomment'

**Comment by do4gr** [comment]
`Added the functions & permissions of template twilio to graphcool.yml as comments.`
`Added the types of template twilio to types.graphql as comments.`
would be my suggestion for the first two lines.
