### ISSUE TITLE
Rename 'target' to 'stage'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#956]
**What feature are you missing?**
The term 'target' used throughout the CLI is confusing. I propose changing the name to 'stage'. It aligns better with DevOps, with other tools (like AWS, Serverless etc.), and you solve the '-t = target vs -t = tail' issue.

**How could this feature look like in detail? Tradeoffs?**
Rename all occurences of target to stage.

**Comment by marktani** [comment]
A target is a neutral, unopinionated entity the CLI can deploy a service too.
We're speccing out a different concept that more closely resembles stages, which we'll introduce further down the road.

Definitely still up for discussion.

**Comment by sorenbs** [comment]
Closed in favour of #1329
