### ISSUE TITLE
`gc deploy --force --dry-run` deploys for real

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#973]
![image](https://user-images.githubusercontent.com/1780597/31853085-7515f8f4-b683-11e7-9f0b-4e06a9295159.png)

**Comment by kbrandwijk** [comment]
Nope, `-d` == 'default', `-D` == 'dry-run'. Confirmed that using `gc -Df` actually does a dry-run...

**Comment by kbrandwijk** [comment]
@marktani close?

**Comment by marktani** [comment]
it's still misleading, maybe switch `-D` and `-d`?

**Comment by timsuchanek** [comment]
I switched `-d` and `-D`, it will be released in `0.9`.

**Comment by kbrandwijk** [comment]
Make sure that you make that change very clear! Because I know a lot of people use scripts, and you have now changed their dry-run script to actually deploy to the default environment, which I think is not optimal!
