### ISSUE TITLE
Request id shouldn't contain eu-west-1 region for local cluster

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#982]
![image](https://user-images.githubusercontent.com/1780597/31853376-8fe0d06a-b687-11e7-8017-531696a7bcb0.png)

probably use `target:simple:id` instead.

**Comment by UADACID** [comment]
i get this one too on local deployment
<img width="551" alt="screen shot 2017-10-31 at 1 22 17 am" src="https://user-images.githubusercontent.com/15373307/32188292-fb855da0-bdd9-11e7-904e-404bf46718b3.png">

**Comment by marktani** [comment]
This is fixed in 0.9.

**Comment by kbrandwijk** [comment]
May I ask how this is fixed?
