### ISSUE TITLE
Playground does not send headers

### ISSUE THREAD

**Issue by wasd171** [graphcool/framework#998]
**Current behavior**
Setting headers in playground ignores them
**Reproduction**
`graphcool playground`
**Expected behavior?**
Headers should be present on every request.

Hi.

I was trying to work with `context.auth`, but it was always `null`. Checking the logs with `graphcool log -f <functionName>` has shown that headers object is empty no matter what headers I set.

**Comment by marktani** [comment]
What's your version for the Playground? Are you using the standalone Electron app, or the one in the browser?

**Comment by wasd171** [comment]
How can I get Playground's version? I am using `graphcool@0.7.0`.
Might be related to https://github.com/graphcool/graphcool/issues/802, I was editing the headers. Deleted all headers and refreshed window, the problem is gone.

**Comment by Alex-Mann** [comment]
I am also using the playground with `graphcool/0.8.5` and when adding header's via the button in the playground nothing is getting sent to my webhook.

**Comment by Alex-Mann** [comment]
I have also tried adding and sending headers with the electron wrapped GraphiQL app + via curl and can confirm the headers are also not passed with those solutions either.

I am running my function as a webhook and am inclined to believe that the headers sent to the Graphcool BaaS are not getting forwarded to my webhook.

**Comment by JonniK** [comment]
Hello, i faced same problem with `graphcool/0.8.5` running framework auth and permissions examples.
I set Authorization header in playground and no headers are present in logs

**Comment by marktani** [comment]
This has been fixed a while ago 🙂
